### ISSUE TITLE
.stop() method should probably disable ArrowUp/ArrowDown/Space?

### ISSUE THREAD

**Issue by thomas-dm** [locomotivemtl/locomotive-scroll#101]
Hello 👋

I’ve just noticed a weird thing with the `.stop()` method: when it’s called, the `wheel` event stops triggering a scroll as it should, but the keystrokes still do.

Is this the expected behavior? This may be a subject of debate, but it certainly feels to me like this method should stop _all_ scrolling and not just the `wheel`/`touchmove` events.

Thanks! 🙏

**Comment by aarongeorge** [comment]
Browsers enable scrolling with arrows and space by default. Are you suggesting that this method disables the browsers native scrolling?

This method is used to stop the library's functionality, not disable the browsers.

**Comment by Jerek0** [comment]
Hi! Thanks for the head's up! 🙏 
We indeed want to disable scroll features induced by `keydown` events when in a stopped state. 

`.stop()` is used to prevent scrolling, it being triggered by a mouse event or not. It's better not to mix native & smooth scrolling behavior 😉
