### ISSUE TITLE
data-scroll-sticky elements lose their target end point if scroll.y != 0

### ISSUE THREAD

**Issue by cmacmillanmarin** [locomotivemtl/locomotive-scroll#105]
Hey 👻!

I noticed an issue with sticky elements losing their target end point when:
- Resizing the browser && scroll is NOT at the top of the page.
- Changing the height of the target element && scroll is NOT at the top of the page. (the issue is present even after calling the instance.update method).

Worth mentioning the issue disappears without reloading the page if you scroll to the top of the page and you resize again, or manually call the update method. The initial point is always well defined, the issue is only present at the target's end.

I thought it might be a declaration issue on my end, but you can find the same issue in your example site as well.

1. Go to https://locomotivemtl.github.io/locomotive-scroll/
3. Scroll down to #scroll-direction
4. Resize the browser
5. Keep scrolling to see the issue

![Screenshot 2020-03-21 at 14 27 42](https://user-images.githubusercontent.com/8655734/77227592-a9168500-6b81-11ea-856f-155a2fc88255.png)

The issue appears independently of the browser you use (Chrome, Firefox or Safari).

Thank you, great library 👊

**Comment by Jerek0** [comment]
Hi! Thanks for the heads up, fixed by #108. 🙂 Please update LS to `3.4.2`
