### ISSUE TITLE
Parallax on images

### ISSUE THREAD

**Issue by fluxxus** [locomotivemtl/locomotive-scroll#106]
On your demo site, in speed control section the first image is not having parallax applied. But the second and third image have it.

How to get it working for regular `img` tags? I've inspected the code, applied to my own code and I only get the scale effect when the image comes into view.

Also, from what I understand the call to `dynamicBackgrounds` doesn't have anything with parallax effect on images.

Can you please shed some light on this, I can't get it to work by using inspector and applying the same code to my case.

**Comment by fluxxus** [comment]
Sorry for the hassle, I have it working now!

**Comment by guyhamilton** [comment]
@fluxxus - how did you get it working? I've been struggling with it. I've got it to work but it jumps when the negative speed is applied.
