### ISSUE TITLE
How to use it with "Barba.js"

### ISSUE THREAD

**Issue by ulziibat-n** [locomotivemtl/locomotive-scroll#109]
Hello. How to use this plugin with barba.js? Is it correct way?
```
const scroll = new LocomotiveScroll({
	el: document.querySelector('[data-scroll-container]'),
	smooth: true,
	getSpeed: true,
	getDirection: true
});
// tell Barba to use the prefetch module
//barba.use(barbaPrefetch);
barba.hooks.afterEnter((data) => {
	scroll.init();
});
barba.hooks.afterLeave((data) => {
	scroll.destroy();
}); 
```

**Comment by vidi45** [comment]
It would be helpful to know this. I also can't get both to work when you go from a page without locomotivescroll to one with locomotivescroll.

**Comment by dngraphisme** [comment]
Hello, same problem. 

I destroy the scroll and reinit in the new page but it does not work either ... If someone has a better track?

Thank you

**Comment by ulziibat-n** [comment]
Hello @dngraphisme 
Here is my solution. Please try it. 

```
const scroll = new LocomotiveScroll({
	el: document.querySelector('.js-scroll'),
	smooth: true,
	getSpeed: true,
	getDirection: true
});
// tell Barba to use the prefetch module
barba.use(barbaPrefetch);

// Init Barba
barba.init({
	requestError: (trigger, action, url, response) => {
        debugger
        // go to a custom 404 page if the user click on a link that return a 404 response status
        if (action === 'click' && response.status && response.status === 404) {
            barba.go( '/404' );
        }
        // prevent Barba from redirecting the user to the requested URL
        // this is equivalent to e.preventDefault()
        return false;
    },
    cacheIgnore: false,
    prefetchIgnore: false,
    timeout: 30000,
    transitions: [
        {
            //sync: true,
            // css classes will look like `.fade-xxx-[-xxx]`
            name: 'fade',
            before({ current, next, trigger }) {
            },
            leave({ current, next, trigger }) {
            },
            afterLeave({ current, next, trigger }) {
				scroll.destroy();
            },
            beforeEnter({ current, next, trigger }) {
            },
            enter({ current, next, trigger }) {
				scroll.init();
            },
			after({ current, next, trigger }) {
				scroll.update();
            },
        }
    ]
});
```

**Comment by dngraphisme** [comment]
> transitions: [
>         {
>             //sync: true,
>             // css classes will look like `.fade-xxx-[-xxx]`
>             name: 'fade',
>             before({ current, next, trigger }) {
>             },
>             leave({ current, next, trigger }) {
>             },
>             afterLeave({ current, next, trigger }) {
> 				scroll.destroy();
>             },
>             beforeEnter({ current, next, trigger }) {
>             },
>             enter({ current, next, trigger }) {
> 				scroll.init();
>             },
> 			after({ current, next, trigger }) {
> 				scroll.update();
>             },
>         }
>     ]

Hello, thanks for your reply and your help but i have a problem with this : my current page does not go to the future page ...

My code :

`// load functions on enter
barba.hooks.beforeEnter((data) => {
    InitAll();
    smoothScroll();
});

function smoothScroll() {
    // smooth-scroll on page
    if ($(".site-content").get(0).hasAttribute("data-smoothscroll")) {

        var scroll = new LocomotiveScroll({
            el: document.querySelector('[data-smoothscroll]'),
            smooth: true,
            smoothMobile: true,
        });

        $('a[href^=\\#]:not([href=\\#])').each(function () {
            var $current = $(this),
                $el = $($current.attr('href'));

            $current.on('click', function (event) {
                event.preventDefault();
                scroll.scrollTo($el.get(0));
            });

        });

        $('#backtotop').on('click', function () {

            var target = document.querySelector('#top');

            scroll.scrollTo(target);
        });

    }
};

barba.hooks.enter(function (page) {
    console.log(page.next.namespace);
    $('body').attr('data-page', page.next.namespace);
});

barba.init({

    timeout: 4000,

    prevent: ({el}) => el.classList && el.classList.contains('prevent'),

    prevent: function (link) {

        if (link.event.type === 'click') {

            // prevent the user to reload the site if a page transition is engaged
            if (barba.transitions.isRunning) {
                link.event.preventDefault();
                link.event.stopPropagation();

                return true;
            }

            // prevent the user to reload the page if the location is the same
            if (link.el.href === window.location.href) {
                link.event.preventDefault();
                link.event.stopPropagation();

                return true;
            }

        }
    },

    transitions: [{
        name: 'legacy-example',
        leave: function(data) {
            var done = this.async();
            TweenMax.to(data.current.container, 1, {
                opacity: 0,
                onComplete: done
            });
        },
        afterLeave: function(data) {
            scroll.destroy();
        },
        enter: function(data) {
            scroll.init();
            var done = this.async();
            TweenMax.from(data.next.container, 1, {
                opacity: 0,
                onComplete: done
            });
        },
        after: function(data) {
            scroll.update();
        },
    }]
});`

**Comment by freieradikale** [comment]
Mine

```
const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true
});
barba.use(barbaCss)
barba.use(barbaPrefetch);
barba.init({
    transitions: [{
        name: "fade",
        beforeEnter() {
            scroll.scrollTo("top")
            scroll.update()
        },
        after() {
        }
    }]
})
```

**Comment by vidi45** [comment]
Hi @ulziibat-n, @dngraphisme can any of you show it on codesandbox.io ?
I have tried all your codes and it still fails me

**Comment by dngraphisme** [comment]
> Hi @ulziibat-n, @dngraphisme can any of you show it on codesandbox.io ?
> I have tried all your codes and it still fails me

Hello @vidi45,

No sorry I have nothing more to show you but here is what to do:

1. Create the barba markups as in the doc: https://barba.js.org/docs/userguide/markup/

2. Declare scroll locomotive in your js

3. Initiate barba (as in the doc too)

4. In the global hooks I did this:
```

barba.hooks.beforeLeave ((data) => {
             scroll.destroy ();
         });

barba.hooks.after ((data) => {
             scroll.init ();
});
```

Logically with all this it should work well.

**Comment by Jerek0** [comment]
I would advise to instantiate LS on an element [inside barba's container (not wrapper)](https://barba.js.org/docs/getstarted/markup/). This way, you destroy it on page leave, then you instantiate the new one on the new page. 

It's easier than trying to keep the same instance and pausing/resuming it.

**Comment by vidi45** [comment]
Like this? I think I already have it like this but it still doesn't work. 

```
<main data-barba="container" data-barba-namespace="home">
   <a class="link" href="about.html">about</a>
   <div data-scroll-container>
        <div>...</div> 
   </div>
</main>
```
and this is my js...

```
const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true
});
 
barba.hooks.beforeLeave((data) => {
    scroll.destroy();
});

barba.hooks.after((data) => {
    scroll.init();
});

barba.init();
```

**Comment by freieradikale** [comment]
Why destroy, the init is still available while using barba. You should only update the position, scroll.update(). Wrong?

**Comment by vidi45** [comment]
It still doesn't work, I always get the following error: "TypeError: Cannot read property 'match' of undefined"

**Comment by freieradikale** [comment]
> It still doesn't work, I always get the following error: "TypeError: Cannot read property 'match' of undefined"

First of all you need a barba wrapper AND a container.

<body data-barba="wrapper">
  

  <main data-barba="container" data-barba-namespace="home">
    
  </main>

  
</body>

**Comment by freieradikale** [comment]
`<body data-barba="wrapper">
  

  <main data-barba="container" data-barba-namespace="home">
    
  </main>

  
</body>`

**Comment by freieradikale** [comment]
First of all you need a warpper AND a container.
https://barba.js.org/docs/getstarted/markup/

**Comment by vidi45** [comment]
I know how a barba works. With other scripts it works for me. It is only with locomotive, so I guess they are incompatible. Or I'm missing something

**Comment by dngraphisme** [comment]
> I would advise to instantiate LS on an element [inside barba's container (not wrapper)](https://barba.js.org/docs/getstarted/markup/). This way, you destroy it on page leave, then you instantiate the new one on the new page.
> 
> It's easier than trying to keep the same instance and pausing/resuming it.

Hello @Jerek0, thanks for your JS LM.

I allow myself to answer this topic with respect to what you said. 

If I use what you say, ie put LM in barba container, with me it does not work. I made tests on a client site, on which I work with barbajs and LM via WP.

**It is rather the reverse that works: Wrapper barba in the body then a div with LM then inside it is container barba**

I know barbajs well and I chat a lot with @xavierfoucrier in charge of this JS.

He will also allow himself to come back to you for compatibility between barbajs2 and LM, especially for the scroll part where we realized that we were forced to use an update while an init is more appropriate I think.

Thank you

**Comment by oguilleux** [comment]
I'm using WordPress, barba.js & LM on this website : https://agentandartists.com

As @Jerek0 said, you need to use a div inside the container. Regarding the project above it's the div `.content`.

But what is tricky is that you need to specify the next container and **NOT** just do `document.querySelector('.content')` (in my case). So I just do :
```
window.wrapper = document.querySelector('.site');
if (barba.data && barba.data.next.container) {
    window.wrapper = barba.data.next.container;
}
```

So LM is init like this :

```
const scroll = new LocomotiveScroll({
    el: window.wrapper.querySelector('.content'),
    smooth: true
});
```

For the hooks, I use :
```
barba.hooks.afterEnter(() => {
    scroll.init();
});

barba.hooks.afterLeave(() => {
    scroll.destroy();
});
```

**Comment by xavierfoucrier** [comment]
Hi everyone,

After a bunch of tests, **LocomotiveScroll is well compatible with BarbaJS**, but you can encounter issues when implementing it. In fact, you need to deal with:

- **The page template**
Having absolute or fixed elements on your page could end in a bad height calculation from LocomotiveScroll, in this case, always put the `data-scroll-container` attribute on the section of your site that scroll. _[(defaults is window.document)](https://github.com/locomotivemtl/locomotive-scroll#instance-options)_

- **Barba page lifecycle**
As Barba makes your site running like a SPA, it won't reload the whole page so the DOM can contain two Barba containers at the same time... and two Locomotive containers too! _[(check the Barba lifecycle documentation)](https://barba.js.org/docs/getstarted/lifecycle/)_

- **LocomotiveScroll settings**
If you don't use the `smooth` option, the library works well as LocomotiveScroll is using `IntersectionObserver` feature... but when `smooth` option is enabled, the library use the `data-scroll-container` element in order to build the scroll, so you need to properly target it when next page is ready. _[(by instantiate LocomotiveScroll again)](https://github.com/locomotivemtl/locomotive-scroll/issues/109#issuecomment-615444536)_.

I will add a dedicated section in the [advanced third party scripts documentation](https://barba.js.org/docs/advanced/third-party/) soon, and a codepen example!

:wink: :v:

**Comment by ulziibat-n** [comment]
@xavierfoucrier Thank you very much.

**Comment by dngraphisme** [comment]
> Hi everyone,
> 
> After a bunch of tests, **LocomotiveScroll is well compatible with BarbaJS**, but you can encounter issues when implementing it. In fact, you need to deal with:
> 
>     * **The page template**
>       Having absolute or fixed elements on your page could end in a bad height calculation from LocomotiveScroll, in this case, always put the `data-scroll-container` attribute on the section of your site that scroll. _[(defaults is window.document)](https://github.com/locomotivemtl/locomotive-scroll#instance-options)_
> 
>     * **Barba page lifecycle**
>       As Barba makes your site running like a SPA, it won't reload the whole page so the DOM can contain two Barba containers at the same time... and two Locomotive containers too! _[(check the Barba lifecycle documentation)](https://barba.js.org/docs/getstarted/lifecycle/)_
> 
>     * **LocomotiveScroll settings**
>       If you don't use the `smooth` option, the library works well as LocomotiveScroll is using `IntersectionObserver` feature... but when `smooth` option is enabled, the library use the `data-scroll-container` element in order to build the scroll, so you need to properly target it when next page is ready. _[(by instantiate LocomotiveScroll again)](https://github.com/locomotivemtl/locomotive-scroll/issues/109#issuecomment-615444536)_.
> 
> 
> I will add a dedicated section in the [advanced third party scripts documentation](https://barba.js.org/docs/advanced/third-party/) soon, and a codepen example!
> 
> 😉 ✌️

Thanks a lot @xavierfoucrier :p

**Comment by xavierfoucrier** [comment]
Hi everyone,

I just add a [dedicated LocomotiveScroll section](https://barba.js.org/docs/advanced/third-party/#Locomotive-scroll) inside the **advanced third party scripts** documentation on the Barba website. Codepen will come later.

Happy reading! :wink: 

> Related Barba repository issue: https://github.com/barbajs/barba/issues/511

**Comment by ulziibat-n** [comment]
Thanks again @xavierfoucrier
