### ISSUE TITLE
Event listeners possible memory leaks

### ISSUE THREAD

**Issue by baptistebriel** [locomotivemtl/locomotive-scroll#11]
Hey guys!

I was looking through the code, super nice work! I've seen a few lines where I think there might be some memory leaks when adding event listeners. When using an arrow function, it will create an anonymous function and therefore the event will not be removed.

When using the `virtual-scroll` module, you'll need to call `this.vs.off(fn)` before calling `this.vs.destroy()` and the function bind needs to be the same.

Instead of:

```javascript
this.vs.on((e) => {})
this.vs.off((e) => {})
```

You should use something like this:

```javascript
this.vs.on(this.event)
this.vs.off(this.event)
```

There is the [same issue](https://github.com/locomotivemtl/locomotive-scroll/blob/master/src/scripts/Smooth.js#L182
) for the `mouseup` and `mousemove` functions:

```javascript
window.addEventListener('mouseup', (e) => this.releaseScrollBar(e))
window.removeEventListener('mouseup', (e) => this.releaseScrollBar(e))
```

It should be something like this. You'll maybe want to create a function inside your class named `onMouseUp`, and call `releaseScrollBar` inside of it.

```javascript
window.addEventListener('mouseup', this.onMouseUp)
window.removeEventListener('mouseup', this.onMouseUp)
```

Hope it helps!
Cheers 🍻

**Comment by antoineboulanger** [comment]
Hey! The `vs.destroy` method already does remove the events from my tests and their docs. You're right for the scrollbar events, thanks for that! It is now fixed in the latest release. Cheers.
