### ISSUE TITLE
General scroll speed / Friction

### ISSUE THREAD

**Issue by dangelion** [locomotivemtl/locomotive-scroll#110]
Hi, is there a parameter to set the general scroll speed of the entire page? A kind of friction.
There's `inertia` that acts when reaching the top and bottom page but I can't find something similar when scroll in the "middle" of the page.

**Comment by Jerek0** [comment]
Hi! 

Please take not that we renamed the `inertia` option to `lerp` with `3.5.0`. 
This setting controls the intensity of the "Linear Interpolation" we apply on the scroll. It won't really affect speed, it's more of an "easing" when you start / stop scrolling. I think [this](https://processing.org/examples/interpolate.html) is a good example to understand that effect.

For the general speed though, we added the `multiplier` option with `3.5.0`. If you set that to `2` your scroll will be twice as fast, `0.5` will make it slower 😉
