### ISSUE TITLE
Stop translating when element is in the middle of the viewport

### ISSUE THREAD

**Issue by thibka** [locomotivemtl/locomotive-scroll#111]
I feel like it's not possible to simply have an element stop parallaxing/moving when it's arrived in the middle of the viewport, ie when the element is "in place". I've tried so many things but nothing works, did I miss something or is it truly not possible with locomotive scroll?
Thanks :)

**Comment by quentinhocde** [comment]
Hi @thibka, 

Indeed It is not possible to have an element which stop its parallax movement. Our library is able to tell you when your element is in the viewport and translating it depending of its speed.

For a custom feature like this I guess you can play with the scroll event and the callback to know when your element is in the middle of your viewport, then you can unset the speed and update() your instance to reload elements.

Thanks ✌️
