### ISSUE TITLE
Scroll container/page height either too long or too short for content on browser window resize

### ISSUE THREAD

**Issue by JonQuayle** [locomotivemtl/locomotive-scroll#112]
Hello 👋

I'm noticing some odd behaviour when re-sizing the browser window after page load. The bottom of the page is either getting cut off or the height of the scroll container is increasing, leaving a blank white area beneath the footer. I thought at first it might be that I am using VH height units in some places - but I would have thought that would be been fine to use?

So far I am noticing this on Safari, Chrome and Firefox on a MacBook. I haven't been testing LS on mobile as I have switched it off for this.

I'm still a bit of a Javascript beginner and after looking at other, similar issues I can see an scroll.update() method that I have tried to use but I can't see any difference, this is my code:

```
const scroll = new LocomotiveScroll({
    el: document.querySelector('#js-scroll'),
    smooth: true,
    smoothMobile: false,
});

window.onresize = updateScroll;

function updateScroll() {
    scroll.update();
};
```

I am also updated to the very latest release so I am up to date. Can anybody shed some light on what is happening please?

Thank you!

**Comment by freieradikale** [comment]
Try this
`window.addEventListener("resize", function(){
   scroll.update();
});`

**Comment by JonQuayle** [comment]
That works perfectly! Thanks @freieradikale
