### ISSUE TITLE
sticky content like section 4 on the demo

### ISSUE THREAD

**Issue by Bouboudlibou** [locomotivemtl/locomotive-scroll#113]
Is it possible with the data-scroll-sticky option to create a fixed section on the left and a scrolling section on the right? 
much like on the editorialnew site? 

with with the following code the content become sticky but no scrolling on right section
```
<section data-scroll-section data-persistent>
    <div id="fixed-elements">
        <div data-scroll data-scroll-sticky data-scroll-target="#fixed-elements">
            <div data-scroll data-scroll-offset="200">
                Fixed elements
            </div>
        </div>
        <div data-scroll  data-scroll-repeat>
            <div id="fixed-target"></div>
            <div data-scroll data-scroll-sticky data-scroll-target="#fixed-target">
                fixed content with a lot of image
            </div>
        </div>
    </div>
</section>
```

**Comment by Jerek0** [comment]
I'm not sure to understand... 🤔

I guess you need to position your two sections side by side w/ CSS. 
Then wrap them inside a container defined by an ID, like `#myarea`. 
Finally, add `data-scroll data-scroll-sticky data-scroll-target="#myarea"` attributes to your left section (the one you want to be sticky). The other one will naturally scroll like the whole page.

**Comment by quentinhocde** [comment]
Hey,

I considerer everything is great ?
Reopen this issue if you need further help!

Thanks
