### ISSUE TITLE
Autoscrolling

### ISSUE THREAD

**Issue by snikhitha095** [locomotivemtl/locomotive-scroll#114]
can i do autoscroll? Instead of using mouse wheel to scroll, Onclick of button automatically scroll the webpage with smooth scroll and parallax effect? How to use locomotive -scroll for autoscroll of the webpage?
And
If i use another plugin for autoscroll, locomotive-scroll's smooth scrolling with parallax effect won't work. Is there any solution?

**Comment by Jerek0** [comment]
Hi, you seem to be looking for the `scrollTo` method described in [this section](https://github.com/locomotivemtl/locomotive-scroll#instance-methods).
Locomotive-scroll will not work with another library unless you write custom code to allow compatibility.
