### ISSUE TITLE
Animating SVG path color while scrolling.

### ISSUE THREAD

**Issue by nashvinxtn** [locomotivemtl/locomotive-scroll#116]
Same like background change color, i am also filing an SVG path in order to have a nice animations. The only problem is while scrolling if the next section contain the SVG path, it freeze for some milliseconds before getting to next section. The cause is mainly if i call SVG like this : 
<svg class="svg" width="1131" height="1138">
     <path fill="#FFFFFF" .... />
</svg>
Any solutions please?

**Comment by nashvinxtn** [comment]
Sorry about this issue, found the solution.

**Comment by williamxsp** [comment]
@nashvinxtn Could you post your solution?
