### ISSUE TITLE
Rotate and scroll

### ISSUE THREAD

**Issue by auriga-z** [locomotivemtl/locomotive-scroll#117]
name: Rotate and Scale
about: Ability to transform the scale and rotation of the element also.
labels: 'Enhancement'

---
---

**Is your feature request related to a problem? Please describe.**
Loco scroll could take over the world if there was an option to not only translate but rotate and scale also with scroll.

**Describe the solution you'd like**
This type of effect can be achieved with https://github.com/alexcambose/motus
But the problem is it only works when the native scroll is enabled and is not as smooth.
It does not work with loco scroll.

**Additional context**
Something similar can be seen on https://www.rino-pelle.com/ in Instagram section of the homepage.

Thanks

**Comment by quentinhocde** [comment]
Hi @auriga-z,

We thinking about it, and we will add a progress value by element to get a value between 0 to 1 when the element is in the viewport. Then you will be able to do what you want with this, like playing a gsap animation.

Thanks!

**Comment by auriga-z** [comment]
@quentinhocde Thanks for the consideration, Does loco scroll works with the new GSAP ScrollTrigger?

**Comment by quentinhocde** [comment]
We really like gsap and we want to open our possibilities to play animations with our scroll values like x, y or speed, but we don't want to add it as dependency to stay opened to using others libraries or other kinds of animations.
ScrollTrigger has some similars concepts of locomotive-scroll but they can't work together because the global vision is different. The best way to animate what you want is to listen the `on scroll` event and play the `progress()` of your animation. You can also trigger an animation with the callback concept, with the `data-scroll-repeat` you can get if the element is entering or leaving the viewport and adapt your animation with it. You can do the same kinds of things but you need to write it differently.

We preparing a new version and it will be available asap, in this commit : https://github.com/locomotivemtl/locomotive-scroll/commit/c12c5b9c081fa8cf01ee5168c35944e9d4e55f9b
We added the capability to get the progress of an element from 0 to 1 when it visible in the viewport. It can be great to play a gsap progress with this value ;) 
✌️

**Comment by auriga-z** [comment]
@quentinhocde  Sorry for asking such dumb question but could you please write an example of how I can do that. Like how can I scrub/Link a gsap animation with the scroll?

**Comment by quentinhocde** [comment]
Yes @auriga-z, I can share with you an example soon 🙂

**Comment by quentinhocde** [comment]
Ok so : https://github.com/locomotivemtl/locomotive-scroll/commit/720eea55efdbdbcdf87386163c0bfc3c067dd678#diff-04c6e90faac2675aa89e2176d2eec7d8

Now, we get all in view elements in the `on scroll` event. You can also add a `data-scroll-id` to your DOMElement to scope it easily.

**In your HTML**
```
<div data-scroll data-scroll-id="test">...</div>
```

**JS**
```
scroll.on('scroll', (args) => {
            if(args.currentElements.find(item => item.id === 'test') !== undefined) {
                let progress = args.currentElements.find(item => item.id === 'test').progress
                console.log(progress)
                // ouput example: {x: 0, x: 0.34}
                // gsap example : myTimeline.progress(progress.y);
            }
}
```

**Comment by quentinhocde** [comment]
It will be release in v`4.0.0` ✌️

**Comment by tiansial** [comment]
Progress seems to be halted during first scroll, just updates when you scroll past the element (using v4 branch)

**Comment by tiansial** [comment]
> Ok so : [720eea5](https://github.com/locomotivemtl/locomotive-scroll/commit/720eea55efdbdbcdf87386163c0bfc3c067dd678)
> 
> Now, we get all in view elements in the `on scroll` event. You can also add a `data-scroll-id` to your DOMElement to scope it easily.
> 
> **In your HTML**
> 
> ```
> <div data-scroll data-scroll-id="test">...</div>
> ```
> 
> **JS**
> 
> ```
> scroll.on('scroll', (args) => {
>             if(args.currentElements.find(item => item.id === 'test') !== undefined) {
>                 let progress = args.currentElements.find(item => item.id === 'test').progress
>                 console.log(progress)
>                 // ouput log example: 0.34
>                 // gsap example : myTimeline.progress(progress);
>             }
> }
> ```

I'm using Highway JS and on onEnterCompleted, I'm doing `this.mainController.updateScroll();` to fix the known issue of LS of not calculating the scroll height correctly and the progress seems to be halted. If I remove scroll.update() progress works ok.

**Comment by JamesHRowe** [comment]
@quentinhocde Just a side note on this. I Have downloaded the v4 branch and tried this progress feature and it works great but has one small issue I'm not sure you might be aware of. The progress property doesn't update on scroll if you resize the window until you are out of the elements view and go back into it.

**Comment by pjguzloz** [comment]
Hello @quentinhocde ,

To make a couple of animations, can I extract the value of an element that increases or decreases at the moment it is displayed with the scroll? From there I can do countless things. That is, an element with "data-scroll="" data-scroll-speed="1.6"" while transforming "transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, -120, 0, 1);" to get the value -120.

To get the scale of this header for example: https://araw.limnia.com

Thank,
