### ISSUE TITLE
Update scrollposition after matrix was manipulated by javascript

### ISSUE THREAD

**Issue by MargadantLuca** [locomotivemtl/locomotive-scroll#118]
First, thank you a lot for this great library. 

I really would like to see an event to update the «scroll-position» after the scrollcontainers matrix was manipulated by javascript.

In my case i wanted to autoscroll the page while the user is not moving his mouse. Works fine, but locomotive-scroll jumps back to his last remebered position when user starts scrolling again.

if I missed something i'm sorry for the request.

**Comment by Jerek0** [comment]
Hi! 

Well, it's a bit underground to manipulate the matrix and your needs are quite specific... 
But let's be wild: I suppose you could achieve what you want in JS by updating `yourLSinstance.scroll.instance.delta.y` to move the vertical scrollposition (smooth only), and call `yourLSinstance.scroll.startScrolling()` after your first scrollposition modification.

My quick working test : 
```JS
// start autoscroll
let i = 0
let myinterval = setInterval(() => {    
    instance.scroll.instance.delta.y+=2
    if(i == 0) instance.scroll.startScrolling()
    i++
}, 16)
```
```JS
// stop autoscroll
clearInterval(myinterval)
```

Again, keep in mind this is underground and unsupported use of our library so use at your own risk 
🙃

**Comment by MargadantLuca** [comment]
Hello,

Thanks a lot for your response. Looks very interesting and i will definitly give it a try next time i'm running into something like that again. 

I forgot to update my request recently. In my case i was manipulating the matrix direct on the element itselfs matrix. So it was independend and therefore locomotive-scroll didn't know where to kick in again and jumped back of course. At the end i made it using the setScroll function of Locomotive-Scroll which i found out it exists by looking through the code. I used it when user starts scrolling again and all worked fine.

Maybe is `setScroll(x,y)` worth to be mentioned in the Docs? 

Have a nice day and thanks again! :)
