### ISSUE TITLE
Stop hover during scroll

### ISSUE THREAD

**Issue by rodolfosarno** [locomotivemtl/locomotive-scroll#119]
Hello,

Locomotive scroll is awesome but I'm hoping to get some help with the way it behaves.
I have this function to stop my cursor hovering elements when I scroll but it doesn't work when Locomotive is on.

```
<style>

.disable-hover,
.disable-hover * {
  pointer-events: none !important;
} 

</style>

<script>

        const delay = 500;  
	let timer;

	window.addEventListener('scroll', function() {
  
  	const bodyClassList = document.body.classList;
  	clearTimeout(timer);
  
    
  	if (!bodyClassList.contains('disable-hover')) {
        bodyClassList.add('disable-hover');
	}
   
 	timer = setTimeout(function() {
         bodyClassList.remove('disable-hover');
        }, delay);
  
        },  false);   

</script>
```

This on the other hand does half of the job but then the scroll stops working after I scroll the 1st time. Sorry about my lack of JS knowledge, but is there a way to make this work with Locomotive?

```
scroll.on('scroll', obj => { 
  document.body.classList.add('disable-hover');
});
```

Thank you

**Comment by Nyshhh** [comment]
hey @rodolfosarno,

Is there a solution for this?
