### ISSUE TITLE
scrollTo() with smoothMobile: false only working in Chrome (Android), not Safari (iOS)

### ISSUE THREAD

**Issue by jarovision** [locomotivemtl/locomotive-scroll#120]
Hello lovely humans :) 

**Describe the bug**
I set `smoothMobile` to `false` as my animations weren't running completely smooth on older devices. I still had anchors on my page, which trigger Locomotive's `scrollTo()` function. But the animation is only working on Android devices, running Chrome. iOS devices running Safari show a direct jump instead.

**To Reproduce**
The same behaviour can be found on the Locomotive [example](https://locomotivemtl.github.io/locomotive-scroll/) site. So to reproduce, just visit it.

**Expected behavior**
Expected behaviour was that the `scrollTo()` functions would still work, including the scroll-to-animation and even though `smoothMobile` is set to `false`. As already said, I did find this expectation to be true in some cases. But I couldn't find a consistency in the behaviour.

**Smartphone iOS**
 - Device: iPhone 7
 - OS: iOS 13.3.1
 - Browser: Safari

**Smartphone Android**
 - Device: Pixel 4
 - OS: 10.0
 - Browser: Chrome Mobile
 - Version: 79

Thank you <3

**Comment by Jerek0** [comment]
Hi! 3c20c548b35a92150bb368a00da3472c7d97e25d should fix this issue. Please upgrade to 3.4.1 😉

**Comment by jarovision** [comment]
thank you so much @Jerek0! when is this release available officially? because i can only see 3.4.0 right now..

**Comment by Jerek0** [comment]
It’s available right now! You can even have 3.4.3 😏
