### ISSUE TITLE
Initial scrollbar fixed

### ISSUE THREAD

**Issue by haroldao** [locomotivemtl/locomotive-scroll#121]
Hello 👋

**Describe the bug**
When I start or reload my page my sidebar is like there
![image](https://user-images.githubusercontent.com/36776278/80529754-38406500-8998-11ea-9a00-4697bc02c3c3.png)

and I have to Zoom in/out to solve "this issue" !

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Thank you 👊

**Comment by haroldao** [comment]
if you want to see my here... here is the link to my repo : https://github.com/haroldao/CosmicWebsite

**Comment by quentinhocde** [comment]
Hi @haroldao,

It will be fixed in 3.4.6 release with this commit https://github.com/locomotivemtl/locomotive-scroll/commit/a5e2381f895911fcca77b21ac8660d391bd79f08

I just check if the container is bigger than the viewport height to display the scrollbar.

Thanks :)
