### ISSUE TITLE
Fixed scroll Indicator with Locomotive Scroll ?

### ISSUE THREAD

**Issue by LaurieVince** [locomotivemtl/locomotive-scroll#124]
Hey, 

I'm wondering if we could create a fixed scroll indicator with Locomotive Scroll in use. 
Here's a preview of what I want to achieve for my blog to indicate the scroll position for the users : 
[https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_scroll_indicator](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_scroll_indicator)

Thanks !!!

**Comment by mrlss** [comment]
Hello. You can easily achieve this, using `scroll` event. Check this out https://codesandbox.io/s/cocky-voice-evo3v?file=/src/index.js
