### ISSUE TITLE
New scrollTo method doesn't work in IE 11

### ISSUE THREAD

**Issue by mrlss** [locomotivemtl/locomotive-scroll#125]
Hello! Thanks for great update to `scrollTo` method, very handy!

However, unfortunately, seems that it is broken when trying to use in in IE11 :( Even on example page - it doesn't work. 

After clicking smoothScroll element - all page elements dissappear and page stop scrolling at all. Only hard reset helps.

Need to revert to previous version because of this :( 
Hope you can take a look into this when have time, cheers

**Comment by Jerek0** [comment]
Thank's for the heads up! 🙂
To get this fix please update LS to `3.4.4`
