### ISSUE TITLE
Can't seem to make the lerp work

### ISSUE THREAD

**Issue by cedrickalegroso** [locomotivemtl/locomotive-scroll#126]
Question 1: I'm trying to use Lerp effect on my text's when scrolling but cant seem to make it work this is the my sample code.     

`<span class="c-lerp-block_title" data-scroll>`
`<span data-scroll data-scroll-delay="0.13" data-scroll-speed="6">S</span>`
`<span data-scroll data-scroll-delay="0.12" data-scroll-speed="6">o</span>`
` <span data-scroll data-scroll-delay="0.11" data-scroll-speed="6">f</span>`
`<span data-scroll data-scroll-delay="0.1" data-scroll-speed="6">w</span>`
`<span data-scroll data-scroll-delay="0.09" data-scroll-speed="6">a</span>`
`<span data-scroll data-scroll-delay="0.08" data-scroll-speed="6">r</span>`
`<span data-scroll data-scroll-delay="0.07" data-scroll-speed="6">e</span>`
`</span>`

added a screen record of whats happening

![issue1](https://user-images.githubusercontent.com/42290274/81522613-b845d200-937d-11ea-9a99-002d3e0900ca.gif)

I copy and pasted the [Js](https://github.com/locomotivemtl/locomotive-scroll/blob/master/dist/locomotive-scroll.min.js) file in the documentation saved it on a local js file then initialize it. 

Question 2: Also another problem I have is when i refresh my browser on a specific section of the page the contents above wont be shown after the reload why? 

![issue2](https://user-images.githubusercontent.com/42290274/81522615-baa82c00-937d-11ea-9bfb-1438e6a792f3.gif)

**Comment by colinduet** [comment]
I have the same problem. Did you already figured this out?

**Comment by princecodes247** [comment]
For question 2, Have you added the locomotive css file?

**Comment by abdi-El** [comment]
> I have the same problem. Did you already figured this out?
The wrapper span and inner spans must have `span:{display: inline-block}`, if you are using bootstrap use `class="d-inline-block"` class on every span and it should work.
