### ISSUE TITLE
scrollTo(0, 0) breaks History API: Scroll restoration

### ISSUE THREAD

**Issue by mrlss** [locomotivemtl/locomotive-scroll#128]
Hello 👋

**Describe the bug**
When using native scroll `smooth: false` page always resetting scroll to top position because of `window.scrollTo(0,0);` in `Core.js` module.

**To Reproduce**
1. Go to any page with `smooth: false` option
2. Init scroll with small delay - `setTimeout(() => initScroll() , 1000)`
3. Scroll down to half of the page
4. See how previous scroll position reset to top after 1 sec

**Expected behavior**
Expect not to reset scroll to top when using `smooth: false` due to the History API scroll restoration. This can be easily achieved just by moving `window.scrollTo(0,0);` from `Core.js` module, to `Smooth.js` module

Thank you 👊

**Comment by mrlss** [comment]
@Jerek0 can you take a look into this? Seems like a fast change, but very important 👊

**Comment by Jerek0** [comment]
Hi, thank's for the heads up 🙂  
Fixed with `3.5.0`
