### ISSUE TITLE
Delegate the Scroll/Touch Event to the document

### ISSUE THREAD

**Issue by Aqro** [locomotivemtl/locomotive-scroll#131]
**Is your feature request related to a problem? Please describe.**
When I have fixed elements outside of the scroll area above my container, the events aren't triggered while hovering them (or touching them on mobile/tablet).

**Describe the solution you'd like**
Maybe provide an option when initializing the scroll to delegate the event listener to the `document` or any other parent rather than the container itself.

**Comment by Jerek0** [comment]
Hi, thank's for the request! We added the `scrollFromAnywhere` option with `3.5.0`, please update & enjoy! 🙃
