### ISSUE TITLE
Hash link breaks

### ISSUE THREAD

**Issue by CHEWX** [locomotivemtl/locomotive-scroll#134]
Hello 👋

**Describe the bug**
When clicking a link with a hash `<a href="#footer">Scroll to Footer</a>`, scroll doesn't scroll and jumps to position, this then creates whitespace at the bottom.

**To Reproduce**
As abive.

**Expected behavior**
Either auto `scrollTo()`, or just jump to section and viewport take into account.

**Screenshots**
Whitespace at bottom of website.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10
 - Browser: Chrome 
 - Version: 83.0.4103.61

Thank you 👊

**Comment by Jerek0** [comment]
Hi! You need to add a `data-scroll-to` attribute to your `a` tag 😉

`<a href="#footer" data-scroll-to>Scroll to Footer</a>`

**Comment by CHEWX** [comment]
Thanks for your quick reply. Yep I know this, but when the link is added via a CMS it's just to put in a failsafe. Something like, click link, it jumps to section, on scroll, check that viewport is still where it should be, if not, recheck position and update.
