### ISSUE TITLE
Page search doesn't scroll to founded results.

### ISSUE THREAD

**Issue by mrlss** [locomotivemtl/locomotive-scroll#136]
Hello 👋

**Describe the bug**
When using `smooth: true` and trying to search on page some information, hitting `Enter` of using arrows of search panel didn't scroll page to results of search

**To Reproduce**
1. Go to any page with `smooth: true`
2. type `ctrl + f`
3. Search for something
4. Try to hit `Enter` to swap search results

**Expected behavior**
Expected to scroll to the position of element that we are searching

** Devices
Any

Thank you 👊

**Comment by Jerek0** [comment]
Hi!

Unfortunately that's something we can't fix 😔

Browser search is a native feature that works with native scroll to go from one result to another in the page. As _locomotive-scroll_ disables native scroll to achieve the smooth effect: it can't work anymore.

We try to support native features as much as we can, unfortunately in that case there is no API or JS events we can rely-on to support such a behavior. Any scroll hijacking library will have the same problem.
