### ISSUE TITLE
Parallax without smooth scrolling?

### ISSUE THREAD

**Issue by LeoSeyers** [locomotivemtl/locomotive-scroll#137]
Hello there,

**Describe the bug**
I'm trying to implement parallax scrolling without smooth scrolling but it doesn't work so far.

**To Reproduce**
I can set up an example but first I want to ask if it's actually in the scope of the librairy.
Smooth scrolling is working fine when I turn it on. When it's turned on, parallax is working as well.
 When it's not, parallax is not working.

``` js
const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
} )
```

`<div data-scroll data-scroll-speed="2" data-scroll-repeat >XXX</div>`

**Expected behavior**
I'd expect parallax scrolling even if smooth scrolling is disabled or I would expect a "caveat" section in the documentation to warn me smooth scrolling should be enabled to benefit from parallax scrolling.

**Desktop (please complete the following information):**
 - W10
 - Chrome
 - latest version

Thanks :))

**Comment by Jerek0** [comment]
Hi! 

Parallax effect only works with smooth effect 😉  As you suggest, we'll update the README.md to make that clear.

**Comment by LeoSeyers** [comment]
@Jerek0 ok, it's what expected thank you :)
