### ISSUE TITLE
Change data-scroll-section to data-scroll-sticky on responsive / media-query

### ISSUE THREAD

**Issue by iamfrankeu** [locomotivemtl/locomotive-scroll#143]
Hello Locomotive and other users,

I'm a beginner at Front-End development, which is using Locomotive scroll for a while now and I'm very positive about it! At the moment I'm struggling with an issue: I would like to create a navigation structure which needs to be relative/absolute on mobile, but fixed on desktop sizes. I use data-scroll-sticky on fixed elements and data-scroll-section on relatives, which both are working great. But how can I change these values for different screen-sizes?

Thanks for your help!

**Comment by coolemur** [comment]
Haven't tried it with locomotive scroll, but maybe this might work (?):

```
window.addEventListener('resize', () => {
  let width = window.innerWidth;
  let breakpoint = 900;
  if (width > breakpoint) {
     // add data-scroll-sticky to sticky navigation element
  }
});
```

**Comment by iamfrankeu** [comment]
Hello @coolemur ,

Thanks for your response! With some add-ons it seems to work like a charm. 

I added a onload event which looks at the current width, so it works from the start. This is my code:
`let currentWidth = window.innerWidth;
        if(currentWidth > breakpoint) {
          element.setAttribute('data-scroll-sticky', '');
        } else {
          element.setAttribute('data-scroll-section', '');
        }
        scroll.update();
      });

      window.addEventListener('resize', () => {
        let width = window.innerWidth;   
        if (width > breakpoint) {
          // add data-scroll-sticky to sticky navigation element
          console.log('bigger than 960');
          element.setAttribute('data-scroll-sticky', '');
          element.removeAttribute('data-scroll-section', '');
        } else {
          // remove data-scroll-sticky from sticky navigation element
          console.log('smaller than 960');
          element.setAttribute('data-scroll-section', '');
          element.removeAttribute('data-scroll-sticky', '');
        }
      });`

Thanks for your help. If nobody got any more comments, I will close the comment.
