### ISSUE TITLE
v4 : (Smooth) Issue with offset calculation in scrollTo method

### ISSUE THREAD

**Issue by boiss** [locomotivemtl/locomotive-scroll#145]
Hello 👋

Working with the v4 in horizontal mode, I had a weird bug that scrollTo would not work as requested.

For some odd reason, sometimes, when scrollTo(domElement) the code that gets the parent Section is not working, so instead of returning [parentSectionOffset] + [elementOffset] it only returns  [elementOffset] 

Since I work with sections in my whole project, to fix it temporarily in my project, i changed at or around Smooth.js:919

```
            if (parentSection) {
                parentSectionOffset = getTranslate(parentSection)[this.directionAxis]; // We got a parent section, store it's current offset to remove it later
            }
```

to this : 
```
            if (parentSection) {
                parentSectionOffset = getTranslate(parentSection)[this.directionAxis]; // We got a parent section, store it's current offset to remove it later
            } else {
                parentSectionOffset = getTranslate(target.closest('[data-scroll-section]'))[this.directionAxis]; // We got a parent section, store it's current offset to remove it later
            }
``` 

Hope this helps

**Desktop (please complete the following information):**
 - OS: All
 - Browser Chrome 
 - Version latest

Thank you 👊

**Comment by Jerek0** [comment]
Hi & thanks for the heads up! 

There was indeed an issue when querying `parentSection`: we recently switched `this.sections` array to an associative array and that prevented `.find()` to work properly.

2f59333 should fix it 🙂
