### ISSUE TITLE
How to call a function every time it appears (reverse)

### ISSUE THREAD

**Issue by luciebachman** [locomotivemtl/locomotive-scroll#147]
Hey,

I just discovered this amazing library, so many thanks to the Locomotive guys that work on it.
I'm wondering if we could use a method that could call a function every time it appears in the viewport. I mean when the user scroll down to discover the website but call the same function when he scrolls up (sort of what ScrollMagic could do with the reverse option). 

I'd like to animate some elements with the GreenSock and need this. Actually I don't see how to resolve that. Anyone ?

Thanks again

**Comment by Jerek0** [comment]
Hi,

You can achieve that by using `data-scroll-call` attribute in pair with `data-scroll` & `data-scroll-repeat`.
It would look like this :
```html
<div data-scroll data-scroll-repeat data-scroll-call="doSomething"></div>
```
```JS
this.scroll.on('call', (value) => {
    if (value === 'doSomething') {
         // Do your thing here
    }
});
```

**Comment by elliottmangham** [comment]
Hey @Jerek0,

This is great although it runs both when it enters the viewport (scroll to it) and also when you leave it (scroll passed it).

Is it somehow possible to keep the repeat for future scrolling up/down, but only have it trigger when at the top of the element by any chance?

Really appreciate the help, thanks!
