### ISSUE TITLE
smooth scroll: iframe causing loss of focus of scroll-container

### ISSUE THREAD

**Issue by bb-richard** [locomotivemtl/locomotive-scroll#152]
Firstly, thanks for the great plugin. I´ve been using it now for while. After some successful applications now, I´ve been running into a strange problem, while using iframes and locomotive.

## Scenario ##
Tested on:
- Firefox / Chrome
- macOS 10.15.6
- scrolling with trackpad

**simple page setup of dom elements like so:**
```html
<div class="smooth-scroll">
    <div data-section="">
        content 1
    </div>
    <div data-section="">
        content 2
        <iframe src="EXTERNAL DOMAIN" style="overflow: hidden; height: 800px; width: 100%;" scrolling="no">
        </iframe>
    </div>
    <div data-section="">
       content 3
    </div>
</div>
```
**locomotive with a pretty basic setup:**

```javascript
const locoScroll = new LocomotiveScroll({
    el: document.querySelector(".smooth-scroll"),
    smooth: true
});
```
## Problem ##
Everything works really smooth, until the mouse-cursor is moved over an iframe and you try to scroll further/back. I´ve tried also `scrollFromAnywhere: true` without any success. It seems the cursor immediately focus onto the iframe. If you move with your mousecursor over a area above or below the iframe the page returns scrollable as desired.

## Request ##
It should be possible to scroll over an iframe, if this is equipped with `overflow: hidden` and a fixed height if smooth scroll is activated.

**Further Thoughts / Alternatives**
Unfortunately the iframe had to remain interactive (with i.e: hubspot forms etc). Any masking won´t do the trick properly. 
Maybe it´s possible handle the specific issue by reposition the iframe outside the scroll-container and applying `position: fixed` and handle the whole thing via a gsap timeline or something similiar. Since Safari don´t show any problems on the desired behaviour, I still have this glimmer of hope this can be fixed in an easier way.

**TODO**
will provide a simple test-scenario on codepen in the next days

**Comment by ashthornton** [comment]
@bb-richard to this day there aren't any solutions to your problem when relying solely on virtual scroll. You have to use workarounds like adding overlays to the iframe, or opening them in modals or similar.

I recently created a smooth scroll package that handles this issue, and other virtual scroll caveats, by falling back to native scroll when virtual isn't available: https://github.com/ashthornton/asscroll

**Comment by bb-richard** [comment]
Hey Ash,
thanks for the fast feedback. I saw ASScroll those days featured on gsap´s scrolltrigger docs and def will try this one out for new projects. looks very promising and quite familiar to locomotive. I will hit u up, when I finished my next page with asscroll. Happy tweening :)
