### ISSUE TITLE
Scroll instance not working on mobile devices

### ISSUE THREAD

**Issue by FearTheWild** [locomotivemtl/locomotive-scroll#158]
Hello 👋

I have a simple scroll instance to tell if the user has scrolled passed 5px, if so it adds class to the header.

```
      scroll.on('scroll', (instance) => {
        if (instance.scroll.y > 5){
          $('.site-header').addClass('is-fixed');
        } else {
          $('.site-header').removeClass('is-fixed');
        }
      });
```

This works great on desktop, but on mobile it doesn't seem to work at all, I have tried setting smoothMobile: true, but that also doesn't seem to fix it.

Am I overlooking something or is this not possible?

Thank you 👊

**Comment by mxmtsk** [comment]
This should work fine. I use pretty much the same code for hiding and showing the header. Does this fail on every mobile (iOS? Android?). Can you provide an example?

**Comment by FearTheWild** [comment]
Sorry, this was user error - it does work as expected. Apologies!
