### ISSUE TITLE
Window height / sections cutoff

### ISSUE THREAD

**Issue by madebyfir3** [locomotivemtl/locomotive-scroll#161]
Hi, ok so the bottom of the page is being cutoff on longer pages and not sure why, seems like this might be an ongoing bug? 
Here's my site typically its this page https://madebyfire.co/about or a case study page https://madebyfire.co/work/american-milsim but when you resize the browser or refresh the page it shows back up correctly.

Using latest 3.6.1
Latest Browsers Chrome, Safari, FireFox

Would appreciate the help, thanks.

Cutoff

<img width="1968" alt="Screen Shot 2020-08-31 at 12 37 56 PM" src="https://user-images.githubusercontent.com/33727176/91744075-e21e4100-eb86-11ea-84c3-68194e20cc71.png">

After Refresh or Resize browser
<img width="1968" alt="Screen Shot 2020-08-31 at 12 38 19 PM" src="https://user-images.githubusercontent.com/33727176/91744111-f19d8a00-eb86-11ea-899d-6aebe1928aad.png">

**Comment by natedin** [comment]
Experiencing similar issue, footer being cut off but on refresh / resize it then appears
