### ISSUE TITLE
Usage with Page Transition Libraries (barba.js)

### ISSUE THREAD

**Issue by ebinabo** [locomotivemtl/locomotive-scroll#166]
Hello 👋

**Transitioning Between Views**
There's a nice example on the [barba.js website](https://barba.js.org/docs/advanced/third-party/#Locomotive-scroll) that shows how to transition between views. However, this fails to work as I tried to reproduce the exact example.

The previous view destroys fine but it doesn't reinitialize the scroller for the next view. I know it's possible to have proper page transitions using this library as I've seen it on the new ITI website and a few others.

Would appreciate the proper syntax of using this library with barbajs or any other page transition libraries.

Thank you 👊

**Comment by 07734** [comment]
Hello, 

Please see the third party documentation for [Barba.js](https://barba.js.org/docs/advanced/third-party/#Locomotive-scroll)

**Comment by ebinabo** [comment]
Thank you, I'll have a look at it
