### ISSUE TITLE
need to change page color on Scroll

### ISSUE THREAD

**Issue by Dushyant1295** [locomotivemtl/locomotive-scroll#171]
Hi Sir  first thank you for this great smooth scroll library 

I need to change page-color (i.e.  data-scroll-container)  like this ref site http://www.amandabraga.com/

and here is the link where  i tried to achieve this
https://pathalgaon.in/ls/

while scrolling on each specific data-scroll-section

it works fine but when  I do reverse scrolling  it  not working properly

       
```
<body>
    <div data-scroll-container class="bg-white">
        <!--white is default body bg -->
        <section data-scroll-section>
           <!-- when it comes on view port it should page color from white  to blue  specified color -->
            <div data-scroll data-scroll-repeat='true' data-scroll-call="bg-blue">
                <img src="img/1.jpg">
           </div>
        </section>
        <section data-scroll-section>
           <!-- when it comes on view port it should page color from blue to red  specified color -->
            <div data-scroll data-scroll-repeat='true' data-scroll-call="bg-red">
                <img src="img/1.jpg">
            </div>
        </section>
    </div>
   <script>
        import LocomotiveScroll from "locomotive-scroll";
        import barba from '@barba/core';

        var scroll;
        function smooth(scrollContainer) {
            let currentScrollContainer = scrollContainer.querySelector('[data-scroll-container]')
            scroll = new LocomotiveScroll({
                el: currentScrollContainer,
                smooth: true,
            });

            scroll.on("call", callValue => {
                if (callValue === "bg-blue") {
                    // currentScrollContainer.className="";
                    // currentScrollContainer.classList.add('bg-blue')
                    // gsap.set(currentScrollContainer,{background:'blueviolet'})
                    currentScrollContainer.style.background = "blueviolet"
                }
            });

        }


        barba.init({
            schema: {
                prefix: 'data-dpk',
            },
            sync: true,
            preventRunning: true,
            transitions: [{
                name: 'dpk-transition',
                 once({ next }) {
                    smooth(next.container);
                },
                leave({ next }) {
                    pageTransition();
                },
                beforeEnter({ next }) {
                    scroll.destroy();
                    smooth(next.container);
                },
            }]
        });
    </script>
</body>
</html> 
```

**Comment by JamesHRowe** [comment]
You may need to supply some example markup but I would make sure `data-scroll-repeat` is on all sections. Then making sure all sections have a color value to reset/remove the active color when they exit or a new section enters.

**Comment by Dushyant1295** [comment]
> You may need to supply some example markup but I would make sure `data-scroll-repeat` is on all sections. Then making sure all sections have a color value to reset/remove the active color when they exit or a new section enters.

Hi @JamesHRowe   Here is my code - Hope that make sance

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Transition</title>
</head>

<body>
    <div data-scroll-container class="bg-white">
        


        <section data-scroll-section>
           
            <div data-scroll data-scroll-repeat='true' data-scroll-call="bg-blue">
                <img src="img/1.jpg">
           </div>
        </section>

        <section data-scroll-section>
           
            <div data-scroll data-scroll-repeat='true' data-scroll-call="bg-red">
                <img src="img/1.jpg">
            </div>
        </section>
    </div>


    <script>
        import LocomotiveScroll from "locomotive-scroll";
        import barba from '@barba/core';

        var scroll;
        function smooth(scrollContainer) {
            let currentScrollContainer = scrollContainer.querySelector('[data-scroll-container]')
            scroll = new LocomotiveScroll({
                el: currentScrollContainer,
                smooth: true,
            });

            imagesLoaded(currentScrollContainer, { background: true }, function () {
                scroll.update();
            });

            scroll.on("call", callValue => {
                if (callValue === "bg-blue") {
                    // currentScrollContainer.className="";
                    // currentScrollContainer.classList.add('bg-blue')
                    // gsap.set(currentScrollContainer,{background:'blueviolet'})
                    currentScrollContainer.style.background = "blueviolet"
                }
            });

        }


        barba.init({
            schema: {
                prefix: 'data-dpk',
            },

            sync: true,
            preventRunning: true,

            transitions: [{
                name: 'dpk-transition',

                 once({ next }) {
                    smooth(next.container);
                },


                leave({ next }) {
                    pageTransition();
                },

                beforeEnter({ next }) {
                    scroll.destroy();
                    smooth(next.container);
                },

            }]
        });


    </script>
</body>
</html>

**Comment by Dushyant1295** [comment]
> You may need to supply some example markup but I would make sure `data-scroll-repeat` is on all sections. Then making sure all sections have a color value to reset/remove the active color when they exit or a new section enters.

Hi @JamesHRowe  I've edited my Question Hope That make Sense 🤍

**Comment by JamesHRowe** [comment]
@Dushyant1295 I presume you are doing a red `if` Check as well with it just not being in this example markup?

If that’s the case does the `data-scroll-call` fire from bottom to top? If it does the calling correctly then it might be the way in which you are changing the styles causing problems. I would recommend a CSS class approach rather than direct style manipulation. This would mean setting an active CSS class as a variable and removing/swapping it out on each `call`.

If it isn’t calling correctly then this might be a bug with this packages calling method but I doubt it. Also a possible solution might be migrating to the v4 branch of this package as it has an updated call method that I find better as it has updated arguments to play with.

I will test this later on to see it this is something I can reproduce for you.

**Comment by Dushyant1295** [comment]
> @Dushyant1295 I presume you are doing a red `if` Check as well with it just not being in this example markup?
> 
> If that’s the case does the `data-scroll-call` fire from bottom to top? If it does the calling correctly then it might be the way in which you are changing the styles causing problems. I would recommend a CSS class approach rather than direct style manipulation. This would mean setting an active CSS class as a variable and removing/swapping it out on each `call`.
> 
> If it isn’t calling correctly then this might be a bug with this packages calling method but I doubt it. Also a possible solution might be migrating to the v4 branch of this package as it has an updated call method that I find better as it has updated arguments to play with.
> 
> I will test this later on to see it this is something I can reproduce for you.

**Comment by Dushyant1295** [comment]
@JamesHRowe 
check this link
  https://pathalgaon.in/ls/

**Comment by Dushyant1295** [comment]
by removing extra margin I fixed  this issue

**Comment by TubeStorm** [comment]
Any fix for this issue, i'm currently faced with the same issue.

**Comment by carlosvolp** [comment]
This work for me!

**HTML code**
```
<div id="body" data-scroll-container>
  <section class="box-item" data-scroll-section>
    <div class="box-item-content" data-scroll data-scroll-repeat data-scroll-call="colorWhite">
      <p>Text....</p>
    </div>
  </section>
  <section class="box-item" data-scroll-section>
    <div class="box-item-content" data-scroll data-scroll-repeat data-scroll-call="colorBlack">
      <p>Text....</p>
    </div>
  </section>
</div>
```

**CSS Style**
```
#body {
  transition: background-color 1s ease;
}
```

**JS Code**
```
const scroller = new LocomotiveScroll({
  el: document.querySelector('[data-scroll-container]'),
  smooth: true
});

scroller.on('call', (value, way, obj) => {
  if (way === 'enter') {
    switch (value) {
      case "colorWhite": 
        document.querySelector('#body').style.backgroundColor = "#FFFFFF";
      break;      
      
      case "colorBlack": 
        document.querySelector('#body').style.backgroundColor = "#000000";
      break;          
    }
  } 
});
```
