### ISSUE TITLE
Add class to body element on scroll

### ISSUE THREAD

**Issue by callmegoon** [locomotivemtl/locomotive-scroll#179]
I have what I feel like should be a simple thing to implement, but I can't figure it out.

I have a fixed header outside of smooth scroll container.  However, I'd like to be able to add a class to the body element after the user scrolls a certain amount down the page.

Before implementing loco, I would just have a simple function that listens for scrolling. Once the scrollTop gets past a certain point, say 100px (so the user has scrolled 100px), I add a class to the body element.  Then I can do things like add a background color to the fixed header or any number of other thing via CSS by targeting that body class.  If you look at this site, you can see an example of what I'm trying to do.  When you scroll, the fixed header gets a black background - https://www.muros.co.

Since there is not actual scrolling happening with loco, I can't figure out what I can listen for that would emulate that same '100px' scroll on the window.

Any tips would be greatly appreciated!

**Comment by chrisvidal** [comment]
start here:

```javascript
const scroll = new LocomotiveScroll();

        scroll.on('scroll', (position, limit, speed, direction) => {
            // add or remove Class to your header            
        });
```

**Comment by callmegoon** [comment]
Nice - got it.  In case it helps anyone else...

```
const locoScroll = new LocomotiveScroll({
  el: document.querySelector(".smooth-scroll"),
  smooth: true
});

locoScroll.on('scroll', (position) => {
  if ((position.scroll.y) > 50) {
    document.querySelector('body').classList.add('scrolled');
  } else {
    document.querySelector('body').classList.remove('scrolled');
  }
});
```

**Comment by mathieupreaud** [comment]
Thanks a lot @callmegoon, exactly what I was looking for.

**Comment by clmsftsw** [comment]
The code is not working for me. I am using Version 4.1 and use Barba for page transitions. 
`const locoScroll = new LocomotiveScroll({
    el: document.querySelector(".smooth-scroll"),
    smooth: true
});

locoScroll.on("scroll", (position) => {
    if ((position.scroll.y) > 50) {
      document.querySelector("body").classList.add("scrolled");
    } else {
      document.querySelector("body").classList.remove("scrolled");
    }
  });`

**Comment by pinkp** [comment]
Doesn't work for me either using 4.1, is there an update / fix?
