### ISSUE TITLE
I dont understand how "Lerp" works

### ISSUE THREAD

**Issue by baccoae** [locomotivemtl/locomotive-scroll#185]
Hello !

I very recently discovered this library and despite my many tries, I can not seem to understand how to work with the Lerp option.

I simply tried to replicate the effect shown in the demo (the letter by letter one), and even when I have the exact same data values, it simply does not work, therefore I suppose my issue lies in the Javascript code, here they are :

My HTML : 
```html              
           [...]
                <span class="test" data-scroll>
                    <span data-scroll data-scroll-delay="0.13" data-scroll-speed="6">This </span>
                    <span data-scroll data-scroll-delay="0.12" data-scroll-speed="6">is </span>
                    <span data-scroll data-scroll-delay="0.11" data-scroll-speed="6">a </span>
                    <span data-scroll data-scroll-delay="0.1" data-scroll-speed="6">paragraph.</span>
                </span>
           [...]
```

And my Javascript :

```js
           import LocomotiveScroll from './node_modules/locomotive-scroll/dist/locomotive-scroll.esm.js';

                const scroll = new LocomotiveScroll({
                el: document.querySelector('[data-scroll-container]'),
                smooth: true,
                multiplier: 0.7,
                lerp: 0.05
          });
```

Thanks in advance !

**Comment by baccoae** [comment]
Nevermind ! I ended up understanding !

For anyone who is in the same case scenario : the <span> you want to be moving must be in a display : "inline-block" in your stylesheet, else it won't move.

Hope that helped 👍

**Comment by dithom** [comment]
I don't understand it as well 😄 It seems `data-scroll-delay` is only working in conjunction with `data-scroll-speed`. But what if i want to create an effect, where an element just has a slight delay to the scroll direction but generally stays in its spot?
