### ISSUE TITLE
Example of new scrollTo()

### ISSUE THREAD

**Issue by elliottmangham** [locomotivemtl/locomotive-scroll#189]
Hello,

Following the 4.0.0 update I see that the `scrollTo` function has been updated:
> Update scrollTo parameters with the options object (offset, duration, easing...).

Is it possible to provide an example of this, please?

I was previously using something like this, which is now unusable:
```js
scroll.scrollTo( 'top', 0, 600, [0.25, 0.00, 0.35, 1.00], true, function() {
     // do something
} );
```

Thank you!

**Comment by elliottmangham** [comment]
Managed to suss it in the end. Here it is, for anyone else in need of an example:
```
scroll.scrollTo( 'top', {
	'offset': 					0,
	'callback': 				function() {
		// do something...
	},
	'duration': 				600,
	'easing':					[0.25, 0.00, 0.35, 1.00],
	'disableLerp': 				true
} );
```

**Comment by zoombree** [comment]
Hi All ,
I have a jquery snippet used to hide/show navbar based on scroll position, unfortunately, it stops working when using "LOCOMOTIVE"

this is the main var used to build logic:
var position = $(window).scrollTop()

thanks for your time & support.

**Comment by AndrewNow** [comment]
Does anyone have an example on how to use this in a React project? I keep getting `scroll.scrollTo() is not a function`

**Comment by Hrobitaillie** [comment]
> Does anyone have an example on how to use this in a React project? I keep getting `scroll.scrollTo() is not a function`

Use it like that:
`    const scrollRef = useRef(null);

    useEffect(() => {
      const scroll = new LocomotiveScroll();
      scrollRef.current = scroll;
      return () => {
        scroll.destroy();
      };
    }, []);

    const handleSmoothScrollClick = () => {
        const sectionSelector = document.getElementById('testing'); //  select your anchor
        scrollRef.current.scrollTo( sectionSelector,  {
	          'offset': 0,
	          'callback': function() {
		          // do something...
	          },
	          'duration': 600,
	          'easing': [0.25, 0.00, 0.35, 1.00],
	          'disableLerp': true
          } )
    }`

**Comment by s3chs** [comment]
> > Does anyone have an example on how to use this in a React project? I keep getting `scroll.scrollTo() is not a function`
> 
> Use it like that:
> 
> ```
> const scrollRef = useRef(null);
>       useEffect(() => {
>         const scroll = new LocomotiveScroll();
>         scrollRef.current = scroll;
>         return () => {
>           scroll.destroy();
>         };
>       }, []);
>  const handleSmoothScrollClick = () => {
>         const sectionSelector = document.getElementById('testing'); //  select your anchor
>         scrollRef.current.scrollTo( sectionSelector,  {
> 	          'offset': 0,
> 	          'callback': function() {
> 		          // do something...
> 	          },
> 	          'duration': 600,
> 	          'easing': [0.25, 0.00, 0.35, 1.00],
> 	          'disableLerp': true
>           } )
>     }
> ```

You are the man <3
