### ISSUE TITLE
Can't scroll on iFrames

### ISSUE THREAD

**Issue by carlfmichel** [locomotivemtl/locomotive-scroll#19]
First of all, thank you for sharing this with the world! I am having an where I can't scroll if my mouse is over an iframe like an embedded youtube video. If I deactivate locomotive-scroll scrolling works as intended. Any ideas on how I can get around this scrolling issue?

Thank you!

**Comment by quentinhocde** [comment]
Hi! Thanks :) 

The mousewheel event propagation doesn't work with an iframe. 

In our projects, we have two solutions : 
- A fullscreen popup to play iframes.
- An overlay with a play/pause button in front of the iframe, which listen a click event to play/pause the iframe.

I hope it will help!

**Comment by carlfmichel** [comment]
Ok, awesome. Thanks for your expert advice! We will implement one on of those solutions.

**Comment by coderesolution** [comment]
Hi, I just wanted to check - is this still the only viable solutions here? @quentinhocde
