### ISSUE TITLE
Disable scroll while modal is open

### ISSUE THREAD

**Issue by amemon0326** [locomotivemtl/locomotive-scroll#193]
Hi all, quick question for you.

Has anyone figured out how to disable scrolling while a modal is open? Normally I would just toggle a `overflow: hidden` class on the `body` tag, but obviously that won't work here. Any ideas?

Thank you!

**Comment by marcoribeiroweb** [comment]
Hi, 
You can use the methods `start()` and `stop()`. When you open the modal set the instance to `stop()` and when you close set back to `start()`.
Hope it helps.

**Comment by amemon0326** [comment]
Thank you!

**Comment by NyanLinSett** [comment]
> Hi, You can use the methods `start()` and `stop()`. When you open the modal set the instance to `stop()` and when you close set back to `start()`. Hope it helps.

Hi, how do I use these methods? Do I apply them in my main javascript file, or in the same file where I called the locomotive module?

With gratitude.
