### ISSUE TITLE
Version 4.x.x doesn't work with Nuxt.js

### ISSUE THREAD

**Issue by grmnn** [locomotivemtl/locomotive-scroll#194]
Hello 👋

I used Locomotive Scroll in an old Nuxt.js project with version 3.5.4 which is working fine. 

Now i started a new project and wanted to use Locomotive Scroll but can't get it to work. 

I am doing it like stated here: https://github.com/locomotivemtl/locomotive-scroll/issues/15#issuecomment-553067908

I get the `"has-scroll-init" ` on my html tag but thats it. If i npm i locomotive-scroll@3.5.4 everything is working without touching anything.

Am I overlooking something or is there something wrong?

Thanks in advance and best regards.

**Comment by CHEWX** [comment]
@ghost What was the issue here? Did you fix? Always worth explaining what happened.
