### ISSUE TITLE
How can I calculate the scroll Percent on page  ?

### ISSUE THREAD

**Issue by Dushyant1295** [locomotivemtl/locomotive-scroll#195]
Hello There ! 
First Thank you for this Great Library 🤍
I want to create Scroll % indicator  

```
>    <div class="baar">
>             <div class="bar1" style="transform: translateX(65%);"></div>
>     </div>
> 
```

![image](https://user-images.githubusercontent.com/47473589/100738960-6ab5b300-33fc-11eb-94a4-07c28bb2422c.png)

**Comment by rutgerbakker95** [comment]
@Dushyant1295 you can use [events](https://github.com/locomotivemtl/locomotive-scroll#with-events) to calculate the scrolling progress:

```js
const bar = document.querySelector('.bar1')

locoScroll.on('scroll', ({ limit, scroll }) => {
  const progress = scroll.y / limit.y * 100

  bar.style.transform = `translate3d(${progress}px, 0, 0)`
})
```

**Comment by Dushyant1295** [comment]
Hey! @rutgerbakker95   Thank you So much

it Was there

![image](https://user-images.githubusercontent.com/47473589/100774736-6bfcd500-3428-11eb-9ee8-f41d384de1ca.png)
