### ISSUE TITLE
Trigger vue method if is-inview via data-scroll-call?

### ISSUE THREAD

**Issue by regenrek** [locomotivemtl/locomotive-scroll#20]
Hey is it possible to trigger events on `data-scroll-section` and do animations with js instead of css? Since I want to use gsap for building the animation timeline

* index.vue / nuxtjs
```html
<template>
  <section>
    <div id="js-scroll" :data-scroll-call="sectionAnimIsInView">
      <div data-scroll data-scroll-speed="1" class="box red"></div>
      <div data-scroll data-scroll-speed="2" class="box blue"></div>
    </div>
  </section>
</template>
<script>
// import TimelineMax from 'gsap/TimelineMax';

export default {
  data() {
    return {
      lmS: null
    };
  },
  mounted() {
    this.lmS = new this.locomotiveScroll({
      el: document.querySelector("#js-scroll"),
      smooth: true
    });
    console.log("lmS", this.lmS);
  },
  methods: {
    sectionAnimIsInView(elems) {
      // const tl = new TimelineMax();
      // tl. .... do something
    }
  }
};
</script>

```

https://codesandbox.io/s/codesandbox-nuxt-7kb0f

**Comment by jp-prieto** [comment]
Hey @regenrek  check this out:

https://codesandbox.io/s/codesandbox-nuxt-mhobt

Hope it helps

**Comment by regenrek** [comment]
It looks kind of a workaround but this is way more than I've expected. Thanks!

**Comment by tiansial** [comment]
> Hey @regenrek check this out:
> 
> https://codesandbox.io/s/codesandbox-nuxt-mhobt
> 
> Hope it helps

How would you abstract data-scroll-call functions to work on every component/page?

Sometimes you would need a generic JS animation on data-scroll-call that would make more sense if it could be called globally.

**Comment by hobbydev71** [comment]
> Hey @regenrek check this out:
> 
> https://codesandbox.io/s/codesandbox-nuxt-mhobt
> 
> Hope it helps

There is a white space at bottom of page.
How can I remove that?

**Comment by altezza04** [comment]
> > Hey @regenrek check this out:
> > https://codesandbox.io/s/codesandbox-nuxt-mhobt
> > Hope it helps
> 
> How would you abstract data-scroll-call functions to work on every component/page?
> 
> Sometimes you would need a generic JS animation on data-scroll-call that would make more sense if it could be called globally.

I guess Just inject the locomotive object into your component , example in Vue 3

In AppVue
`
    provide("scrollerObj", scrollerObj);

`
In your component 
`  
    const scrollerObj = inject('scrollerObj')
    onMounted(() => {
      scrollerObj.value.on('call', {
      // Your Code
      })
    });
`
