### ISSUE TITLE
4.x.x doesn't run

### ISSUE THREAD

**Issue by Virus936** [locomotivemtl/locomotive-scroll#201]
Hello 👋🇨🇵️

**Describe the bug**

I'm trying to learn Locomotive Scroll with the bundler parceljs. 
I start with the fisrt example in the documentation. But nothing work, so i try with 3.6.1 and everything is perfectly fine.

With the 4.0.4, I get the "has-scroll-init" on my html tag and no error message. If i npm i locomotive-scroll@3.6.1 everything is working with the exact same code.

It seems that i'm the only one concerned by this probleme. Do i need to install something to make it work ?

Here is my configuration : 
 - OS: Ubuntu 20.04
 - Browser firefox
 - Version last

Thank you 👊

**Comment by Virus936** [comment]
hello again, 
it seems that the 4.0.6 fixed everything !

**Comment by zeromanser** [comment]
> Hello 👋🇨🇵️
> 
> **Describe the bug**
> 
> I'm trying to learn Locomotive Scroll with the bundler parceljs.
> I start with the fisrt example in the documentation. But nothing work, so i try with 3.6.1 and everything is perfectly fine.
> 
> With the 4.0.4, I get the "has-scroll-init" on my html tag and no error message. If i npm i locomotive-scroll@3.6.1 everything is working with the exact same code.
> 
> It seems that i'm the only one concerned by this probleme. Do i need to install something to make it work ?
> 
> Here is my configuration :
> 
> * OS: Ubuntu 20.04
> * Browser firefox
> * Version last
> 
> Thank you 👊

Yep, exactly same problem. Vue 3 + locoscroll 4

**Comment by JoseGabriel-web** [comment]
> Hello 👋🇨🇵️
> 
> **Describe the bug**
> 
> I'm trying to learn Locomotive Scroll with the bundler parceljs.
> I start with the fisrt example in the documentation. But nothing work, so i try with 3.6.1 and everything is perfectly fine.
> 
> With the 4.0.4, I get the "has-scroll-init" on my html tag and no error message. If i npm i locomotive-scroll@3.6.1 everything is working with the exact same code.
> 
> It seems that i'm the only one concerned by this probleme. Do i need to install something to make it work ?
> 
> Here is my configuration :
> 
> * OS: Ubuntu 20.04
> * Browser firefox
> * Version last
> 
> Thank you 👊

It has been the same for me I am using react - typescript, and had to use -v 3.6.1, did you notice any feature that's not available in this version?

**Comment by zeromanser** [comment]
> > Hello 👋🇨🇵️
> > **Describe the bug**
> > I'm trying to learn Locomotive Scroll with the bundler parceljs.
> > I start with the fisrt example in the documentation. But nothing work, so i try with 3.6.1 and everything is perfectly fine.
> > With the 4.0.4, I get the "has-scroll-init" on my html tag and no error message. If i npm i locomotive-scroll@3.6.1 everything is working with the exact same code.
> > It seems that i'm the only one concerned by this probleme. Do i need to install something to make it work ?
> > Here is my configuration :
> > 
> > * OS: Ubuntu 20.04
> > * Browser firefox
> > * Version last
> > 
> > Thank you 👊
> 
> It has been the same for me I am using react - typescript, and had to use -v 3.6.1, did you notice any feature that's not available in this version?

Try to check screen size (if dev panel opened). It could use locomotive "tablet mode" and disable smooth scroll
