### ISSUE TITLE
Smooth scroll not initializing on mobile view

### ISSUE THREAD

**Issue by a-r-t-y** [locomotivemtl/locomotive-scroll#202]
Hello 👋, 

I am having trouble getting the smooth scroll to initialize in mobile view (currently in Chrome). From what I've read I thought adding `smoothMobile: true ` would sort it but still no luck. 

**My code is:**

```
var scroll = new LocomotiveScroll({
   el: document.querySelector('[data-scroll-container]'),
    smooth: true,
    smoothMobile: true,
    getDirection: true
});
```

This is what is initialized in `<html>` on desktop vs mobile view

**Mobile**
![mobile-view](https://user-images.githubusercontent.com/13275757/101900738-e5729100-3ba7-11eb-93a8-cef45d7d1fef.jpg)

**Desktop**
![desktop-view](https://user-images.githubusercontent.com/13275757/101900741-e86d8180-3ba7-11eb-8844-4a48af3d4ffc.jpg)

Any suggestion as to what I'm missing?

Thank you

**Comment by ziadalzarka** [comment]
This is happening with me right now

**Comment by quentinhocde** [comment]
Hello!

Wich version do you use ? On the v4.0 `smoothMobile` is not available. You can check the [readme](https://github.com/locomotivemtl/locomotive-scroll#instance-options), there is a context scope now.

You can do this : 
```
var scroll = new LocomotiveScroll({
     el: document.querySelector('[data-scroll-container]'),
     smooth: true,
     mobile: {
        smooth: true
    },
    tablet: {
        smooth: true
    }
});
```

**Comment by postite** [comment]
thx ! just had this issue ...
correction : isnt'it "smartphone' instead of mobile ?

**Comment by a-r-t-y** [comment]
Thank you @quentinhocde I updated to 4.0.x and overlooked that. It's working now.

@postite is correct, it using `smartphone `rather than `mobile`.

```
var scroll = new LocomotiveScroll({
     el: document.querySelector('[data-scroll-container]'),
     smooth: true,
     smartphone: {
        smooth: true
    },
    tablet: {
        smooth: true
    }
});
```

Thanks again
