### ISSUE TITLE
scrollingClass is applied on mouseup event

### ISSUE THREAD

**Issue by Djules** [locomotivemtl/locomotive-scroll#204]
Hello 👋

**Describe the bug**
With option `{ smooth: true }`, the `scrollingClass` is added to `<html>` class on `mouseup` event, so the scrollbar appears whereas no scroll event occured.

**To Reproduce**
1. Maintain mouse click anywhere in the page, trying not to scroll
2. Release mouse click
3. See `has-scroll-scrolling` being added to `<html>` class

**Expected behavior**
As no scroll occur, this class shouldn't be added to `<html>` element.

**Hint to fix this issue**
The `scrollingClass` is added in the `releaseScrollBar` method of `Smooth` class.
https://github.com/locomotivemtl/locomotive-scroll/blob/master/src/scripts/Smooth.js#L490

I think the `isScrolling` flag should be checked to know if the `scrollingClass` should be applied or not.

Thank you 👊

**Comment by xavierfoucrier** [comment]
Good catch, same on my side :bug: 

> In addition, the class won't be removed from the `<html>` element until the next scroll event.

**Comment by canadianeagle** [comment]
Can confirm I'm also noticing this in my project!

**Comment by mrlss** [comment]
Hi there 👊   Any updates on this issue?  Would be great to see it fixed 🙃

**Comment by Mitsuriou** [comment]
Having the same issue here; bump! :)

**Comment by brian-cross** [comment]
I have the same issue. It's minor but it would be nice to see it fixed.
