### ISSUE TITLE
You can't scroll when your mouse is over an iframe

### ISSUE THREAD

**Issue by nickchartier11** [locomotivemtl/locomotive-scroll#205]
Hello 👋

**Describe the bug**
You can't scroll when your mouse is over an iframe

**To Reproduce**
1. Embed a youtube iframe
2. Try to scroll when your mouse is over it

**Expected behavior**
You should be able to scroll even if your mouse is over an iframe

**Desktop (please complete the following information):**
MacOS 10.15.7 with Chrome Version 87.0.4280.88 (Build officiel) (x86_64)

Thank you 👊

**Comment by 19h47** [comment]
Hello @nickchartier11!

Unfortunately, there is no mousewheel event propagation on iframe 

What you can do it's add an overlay over the iframe and handle the click event to play/pause the video.

See #19

**Comment by coderesolution** [comment]
Hi, I just wanted to check - is this still the only viable solutions here? @19h47

**Comment by 19h47** [comment]
Hello @coderesolution, I'm afraid yes. 

The reason why you can't capture event on iframe is because event is design to bubble into a tree and iframe is a separate tree [@see](https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-flow-capture)

**Comment by coderesolution** [comment]
Hey @19h47, I see, thank you for the prompt confirmation.

I guess videos have easy workarounds (custom play buttons), but I am working on a singer/artist website which requires iFrames for Spotify, Apple Music, Amazon Music, etc. so as you can imagine these need full interaction. I wondered if you have any suggestions for workarounds (without sacrificing Locomotive, obviously).

Appreciate your input, thanks again!

**Comment by 19h47** [comment]
@coderesolution I can imagine the frustration. Maybe disable smooth scroll on this particular page?

**Comment by coderesolution** [comment]
Thanks @19h47, I will weigh up the options! Appreciate your time.

**Comment by Dushyant1295** [comment]
in some cases  where our video is on autoplay and on loop we can use 
pointer-events: none 
```

iframe{
  pointer-events:none;
}
```

**Comment by therodrigot** [comment]
worked with something like:

`scroller = new LocomotiveScroll({
  el: document.querySelector("[data-scroll-container]"),
  smooth: true,
});
$(".my-iframe-class").on("mouseenter", scroller.stop);
$(".my-iframe-class").on("mouseleave", scroller.start);`

**Comment by migueltrias** [comment]
Has anyone come up with a more usable solution than just disabling pointer events?

It happens with many iframes like google maps, youtube and vimeo videos, 3d configurator embeds, etc... I happen to have a website fully populated of these frames and the experience is awful, turning a transform-based scroll pretty much useless... :/

**Comment by Sandstedt** [comment]
Added a little UX thingy to @migueltrias's answer. On all your iframe's parent elements, add the class `.iframe-parent` and then add this CSS to your page, and the cursor will change to a spinner while we wait for the scrolling to stop:

```css
.has-scroll-scrolling iframe {
  pointer-events: none;
}
.has-scroll-scrolling .iframe-parent {
  cursor: wait;
}
```

**Comment by krzysztofGwozdz** [comment]
@Sandstedt @migueltrias @nickchartier11 
If you want be able to scroll while hovering over the iframe simply add invisible pseudoelement to the iframe-parent.

```
.iframe-parent {
     position: relative;

     &:before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
 }
```

There is no need to add `pointer-events: none;` to the iframe element.

**Comment by curtismccaw** [comment]
Hi there, i'm experiencing this issue. How can we resolve it? None of the suggestions above fix it. 
Seems to be when the user lands in the middle of a full screen iframe they're unable to scroll regardless of what we do.

**Comment by krzysztofGwozdz** [comment]
@curtismccaw my solution works well for me. Try to add invisible pseudo element to the iframe parent and make sure is at the top of the iframe (play with z-index if needed).

**Comment by sushanyadav** [comment]
> @Sandstedt @migueltrias @nickchartier11 If you want be able to scroll while hovering over the iframe simply add invisible pseudoelement to the iframe-parent.
> 
> ```
> .iframe-parent {
>      position: relative;
> 
>      &:before {
>         content: '';
>         position: absolute;
>         top: 0;
>         left: 0;
>         width: 100%;
>         height: 100%;
>     }
>  }
> ```
> 
> There is no need to add `pointer-events: none;` to the iframe element.

Thank you @krzysztofGwozdz .This solution worked for me.  I was experiencing issues in Safari, but now it works well. 👍

**Comment by migueltrias** [comment]
> @Sandstedt @migueltrias @nickchartier11 If you want be able to scroll while hovering over the iframe simply add invisible pseudoelement to the iframe-parent.
> 
> ```
> .iframe-parent {
>      position: relative;
> 
>      &:before {
>         content: '';
>         position: absolute;
>         top: 0;
>         left: 0;
>         width: 100%;
>         height: 100%;
>     }
>  }
> ```
> 
> There is no need to add `pointer-events: none;` to the iframe element.

Hi,
While this solution allows for scrolling if the mouse is over an iframe, it renders its below elements useless as the :before layer will still remain on top. So, I wouldn't say the issue is resolved :/

**Comment by krzysztofGwozdz** [comment]
> Hi, While this solution allows for scrolling if the mouse is over an iframe, it renders its below elements useless as the :before layer will still remain on top. So, I wouldn't say the issue is resolved :/

Hey,
You can't eat cake and have cake :) 

If you are referring to video controls that you can't use, I encourage you to create custom playback controls.

**Comment by migueltrias** [comment]
> > Hi, While this solution allows for scrolling if the mouse is over an iframe, it renders its below elements useless as the :before layer will still remain on top. So, I wouldn't say the issue is resolved :/
> 
> Hey, You can't eat cake and have cake :)
> 
> If you are referring to video controls that you can't use, I encourage you to create custom playback controls.

For video yes, that's the solution right now. But for more complex embeds, this is still a huge problem (i.e. product configurators from third parties, interactive catalogues, etc.).

**Comment by devshum** [comment]
> @Sandstedt @migueltrias @nickchartier11 If you want be able to scroll while hovering over the iframe simply add invisible pseudoelement to the iframe-parent.
> 
> ```
> .iframe-parent {
>      position: relative;
> 
>      &:before {
>         content: '';
>         position: absolute;
>         top: 0;
>         left: 0;
>         width: 100%;
>         height: 100%;
>     }
>  }
> ```
> 
> There is no need to add `pointer-events: none;` to the iframe element.

Thanks, works well

**Comment by Voltra** [comment]
Just to clarify for future references: thus far it's not possible to scroll over an iframe smoothly without compromising pointer events propagation, starting stationary or already scrolling.

**Comment by Voltra** [comment]
Everything in the iframes are usable as usual. It's just that if you started scrolling a while back and your cursor enters an iframes, your scrolling is abruptly halted

**Comment by railsfactory-robin** [comment]
if anyone facing the same issue with lenis scroll please try the below css.

.lenis-smooth .react-player::before{
  content: "";
  position: absolute;
  height: 100%;
  width: 100%;
}

note: react-player (wrapper class for  'react-player/vimeo') react-player/vimeo rendering iframe, so while scrolling we can add this pseudo class

**Comment by fultonoff** [comment]
> if anyone facing the same issue with lenis scroll please try the below css.
> 
> .lenis-smooth .react-player::before{ content: ""; position: absolute; height: 100%; width: 100%; }
> 
> note: react-player (wrapper class for 'react-player/vimeo') react-player/vimeo rendering iframe, so while scrolling we can add this pseudo class

But then i cant click

**Comment by railsfactory-robin** [comment]
> > if anyone facing the same issue with lenis scroll please try the below css.
> > .lenis-smooth .react-player::before{ content: ""; position: absolute; height: 100%; width: 100%; }
> > note: react-player (wrapper class for 'react-player/vimeo') react-player/vimeo rendering iframe, so while scrolling we can add this pseudo class
> 
> But then i cant click

I dont think any problem on clicking it because while scrolling only the class lenis-smooth is attached to the dom if u r not scrolling it wont be there. Please check carefully while scrolling what class is getting attached to the html tag in the root. Write the css accordingly

**Comment by fultonoff** [comment]
@railsfactory-robin Thanks for your reply, see i'm using it in nextjs, this is what i did in CSS: 
.lenis.lenis-smooth .react-player::before{
  content: "";
  position: absolute;
  height: 100%;
  width: 100%;
  } but it's not working
