### ISSUE TITLE
Updating scrollbar when chaging page

### ISSUE THREAD

**Issue by mesagoul** [locomotivemtl/locomotive-scroll#21]
Hi there,

I'm using your locomotive-scroll library with smooth for my fullAjax website and i'm encountering a problem with the scrollbar when I'm browsing to another page. It's height (relative to the height of the page) is never updated.

When i browse to another page, i call the `update ()` instance method but I cannot find any code to update scrollbar size inside this method.

So I manually update it like in your `initScrollBar()` method : 
```
this.scrollbarThumb.style.height = `${(window.innerHeight * window.innerHeight) / (this.instance.limit + window.innerHeight)}px`;
this.scrollBarLimit = window.innerHeight - this.scrollbarThumb.getBoundingClientRect().height;
```
Is there another way to fixed this, or perhaps i do something wrong ?

Thank you 😄

**Comment by fedeweb** [comment]
Hi @mesagoul how did you solve the issue?

Thanks!
