### ISSUE TITLE
What exactly is data-scroll-delay?

### ISSUE THREAD

**Issue by regenrek** [locomotivemtl/locomotive-scroll#22]
Hi,

as far as I understand you should use the `transition-delay` property to time your animations correctly. What is the purpose of `data-scroll-delay` then? Or how I can interpret the meaning of `lerp`. Thanks!

Regards

**Comment by quentinhocde** [comment]
Hi! 

Sorry for the late answer, the `data-scroll-delay` is using for parallax elements if you want to add a `lerp` on it. In the demo you can test it with the third section :)

Thanks
