### ISSUE TITLE
Play/pause video on scroll

### ISSUE THREAD

**Issue by mathieupreaud** [locomotivemtl/locomotive-scroll#223]
Hi,

I have a function to play/pause a video on scroll when visible. The thing is that the video is inside my smooth scroll container. So the function is not working. I'm struggling to make it work with Locomotive scroll. Here is the JS code:

```
var videos = document.getElementsByTagName("video");

  function videoScroll() {
      var fraction = 0.5;

      for(var i = 0; i < videos.length; i++) {

          var video = videos[i];

          var x = video.offsetLeft, y = video.offsetTop, w = video.offsetWidth, h = video.offsetHeight, r = x + w,
              b = y + h, //bottom
              visibleX, visibleY, visible;

              visibleX = Math.max(0, Math.min(w, window.pageXOffset + window.innerWidth - x, r - window.pageXOffset));
              visibleY = Math.max(0, Math.min(h, window.pageYOffset + window.innerHeight - y, b - window.pageYOffset));

              visible = visibleX * visibleY / (w * h);

              if (visible > fraction) {
                  video.play();
              } else {
                  video.pause();
              }
      }
  }

  window.addEventListener('scroll', videoScroll, false);
  window.addEventListener('resize', videoScroll, false);
```

Any help would be much appreciated, thanks!

**Comment by saidMounaim** [comment]
**HTML**

`<video id="video" data-scroll data-scroll-class="videoPlay" data-scroll-repeat="true" ></video>`

**JS**

`
const video = document.getElementById("video");

scroll.on('scroll', (args) => {

	if(video.classList.contains("videoPlay")) {
			video.play();
	} else {
			video.pasue();
	}

})
`

**Comment by saidMounaim** [comment]
**HTML**

`<video id="video" data-scroll data-scroll-class="videoPlay" data-scroll-repeat="true" ></video>`

**JS**

`const video = document.getElementById("video");
scroll.on('scroll', (args) => {
	if(video.classList.contains("videoPlay")) {
		video.play();
	} else {
		video.pasue();
	}
})`

**Comment by mathieupreaud** [comment]
Thank you @saidMounaim 

Unfortunately it doesn't work. I have this error in the console:

`Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

The issue happens each time the video is inview and refers to the line `video.play();` or `video.pause();`

**Comment by mathieupreaud** [comment]
After searching some similar issues. It seems the user agent is blocking the autoplay. So I just insert autoplay property in the video tag and it works like a charm.

Thanks!
