### ISSUE TITLE
How to get the percentage/current scroll value?

### ISSUE THREAD

**Issue by marxcie** [locomotivemtl/locomotive-scroll#224]
Hi! I understand how to get if an element in view, but how to get the scroll position or percentage for the complete data-scroll-container?  

Like if I'd like to have a progress bar for the full content section. Actually, I'd like to have a very slow Y background animation scroll for complete pages. (Sorry, my JS knowledge is very limited.)

Thank you! 

![scrollexplanation](https://user-images.githubusercontent.com/15873939/106261093-76b5c980-6221-11eb-93b8-f5271222ee08.png)

**Comment by saidMounaim** [comment]
**HTML**

`<h1 data-scroll data-scroll-id="hey">Hey</h1>
`
**JS**

**scroll.on('scroll', (args) => {
    // Get all current elements : args.currentElements
    if(typeof args.currentElements['hey'] === 'object') {
        let progress = args.currentElements['hey'].progress;
        console.log(progress);
        // ouput log example: 0.34
        // gsap example : myGsapAnimation.progress(progress);
    }
}**

**Comment by marxcie** [comment]
Thank you, but as I've read, it says All `data-scroll` elements have a progress value. So, I can get the progress of element A, element B, and so on, after each other, but it applies only to `data-scroll` elements, and I'd like to know the progress of the `data-scroll-container`.

Or the only way is adding an ID for all the `data-scroll` elements, and trying to calculate the `data-scroll-container` progress out of it? (I guess that's not the way, every data-scroll element can have different heights, they can be absolute positioned, etc...)

**Comment by marxcie** [comment]
Sorry for opening the topic, I've found my answer here: 
[](https://github.com/locomotivemtl/locomotive-scroll/issues/195)

I missed this question was answered already. I'm closing this now.
