### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by FloLech** [locomotivemtl/locomotive-scroll#226]
I am facing the challange of getting locomotive scroll to work with my angular (version 11) project.
It would be cool to have some wrapper for locomotive, so the library can be used by angular direcitves.
I tried using the locomotive as a library dependency, but faced issues reagrding height (bottom cut off, .update() running on interval).
Is there some source, that might help me get started?

**Comment by FloLech** [comment]
As I was struggeling with getting Locomotive Scroll to work with Angular I decided to write a small tutotial on how to get started. You can find the guide here: https://flo-lech.medium.com/using-locomotive-scroll-with-angular-a5e9049233dd

**Comment by filipwiniarski** [comment]
@FloLech Small note - with `OnInit` implementation you will miss dynamic content which then will not be taken in consideration by Locomotive scripts. If your site uses content projection, loops, etc... you will have to use `AfterViewInit`.
