### ISSUE TITLE
Support for screen smaller than 1024 pixels

### ISSUE THREAD

**Issue by olivierlarose** [locomotivemtl/locomotive-scroll#227]
**Is your feature request related to a problem? Please describe.**
I see that the smooth scroll doesn't seem to be working on screens smaller than 1024px, is there a reason for that?

**Describe the solution you'd like**
I would like it to have a smooth scroll on smaller screens

**Comment by marcoribeiroweb** [comment]
Duplicate of #202 ?

**Comment by mirc1one** [comment]
Well AFAIK you only need smooth scrolls for desktops using mouse, mousewheel is choppy. But when using swiping on either trackpad or mobile device you already have a smooth effect because inertia.

**Comment by olivierlarose** [comment]
> Well AFAIK you only need smooth scrolls for desktops using mouse, mousewheel is choppy. But when using swiping on either trackpad or mobile device you already have a smooth effect because inertia.

Yes but I’m talking about small desktop screens using mouse. Under 1024px is not supported by default. I think @marcoribeiroweb is correct, I didn’t realize they changed the keys to force smooth scroll on smaller devices.
