### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by fedeweb** [locomotivemtl/locomotive-scroll#23]
Hi,

I need the horizontal scroll for a specific page and I tried to change the direction option to "horizontal" without any effect.

Could you give me some hints to have the horizontal scroll, like you did for this website?

https://homesociete.ca/

Thanks!

**Comment by quentinhocde** [comment]
Hi 👋

We started to anticipate an horizontal scroll mode, but for now with the v3, you can't 😕

[https://homesociete.ca/](url) was made with an older version (v2), and many things was custom to manage the horizontal scroll. 
Maybe the best solution for you is to fork the locomotive-scroll v3, and affect all transforms with the direction.

✌️

**Comment by andrewjireland** [comment]
Hey, I ran into the same problem trying to get the horizontal option to work — it would be nice if this was clearer in the docs.

Apologies for the newb question, but would updating the `transform` function transform matrix be enough to enable horizontal scrolling for forked use?

**Comment by lackmy** [comment]
Hey, great job on the script. 

I have tried, however, to be useful for horizontal navigation. 
with: direction: 'horizontal',

but it doesn't work 😕 

Do you have an idea how to navigate with just a horizontal scroll bar?  
thank you

**Comment by proov** [comment]
Hello,

After  a quick reading of the documentation, i've seen "direction" option on the container, so i sold a horizontal scrolling site to my client Ahahaha. i tried today with direction: 'horizontal' but it wont work. Still no news about horizontal scrolling ? The CSS scrollbar with/height is coded to be vertical, so i think, it's not implemented yet.

@quentinhocde i'm interested in your workaround, to fork and replace the directions. Is it hard to do ?

**Comment by Jerek0** [comment]
This feature is a work in progress. You can try cloning the [`horizontal-v3`](https://github.com/locomotivemtl/locomotive-scroll/tree/horizontal-v3) branch and take a look at [this example](https://github.com/locomotivemtl/locomotive-scroll/blob/horizontal-v3/docs/horizontal.html). But keep in mind it's a WIP.

**Comment by proov** [comment]
Thanks @Jerek0 i tried the smooth-scrolling by Baptiste Briel and the WIP horizontal-v3, i have better results with the Locomotive Scroll. And i didnt get any bugs or weird things yet. Really good library, you really did an amazuing work here 🙏 

I will beta test it on a real site :D

**Comment by proov** [comment]
Hello @Jerek0, do you think i can port this commit on the horizontal-v3 or it's a dead end 😅 ? https://github.com/locomotivemtl/locomotive-scroll/commit/bca039168e5be26a89ccd3704c113ba4c565c104

**Comment by quentinhocde** [comment]
Hello @proov, 

We will try to merge the horizontal-v3 asap, we can try to merge this commit on your side if you want, but maybe it can be a bit messy 😅

**Comment by proov** [comment]
That would be wonderfull ! 😍 

I have a dead line for mid-June. You think you guys can merge it before ? otherwise, it's not a big deal. I'll try to port the scrollTo improvement myself, and mention it's a fork / beta version of the locomotive-scroll-v3 😅

**Comment by schegolev-dev** [comment]
Hi! Thank you guys for the amazing product! 

I'm using v3.5.4 for a horizontal scrolling website, and when I upgrade to version 4, a horizontal scroll does not work and an error occurs in the console: 'TypeError: LocomotiveScroll is not a constructor'. When I coming back to version "3.5.4" everything works fine again.

```
const scroll = new LocomotiveScroll({
            el: document.querySelector('[data-scroll-container]'),
            smooth: true,
            direction: "horizontal",
            lerp: 0.05
        });

```
Maybe someone knows why it's happened?

**Comment by vidi45** [comment]
I'm using this example[https://github.com/locomotivemtl/locomotive-scroll/blob/horizontal-v3/docs/horizontal.html](url), but I cannot access event instances in this way. Any suggestion?

**Comment by fedeweb** [comment]
Hi guys! I'm using your plugin in some websites and I'm really happy with it. Thanks!

Do you have any idea on when you will merge the branch horizontal-v3 :) ?

**Comment by iamfrankeu** [comment]
> You can have a look of how your horizontal-beta perform in real world : https://www.soubil-luberon.fr/ 😁

It looks amazing but I still don't know how it works. 😢 My site keeps showing everything vertical.
