### ISSUE TITLE
Option to disable scroll on spacebar event

### ISSUE THREAD

**Issue by eugjlee** [locomotivemtl/locomotive-scroll#24]
VirtualScroll takes a spacebar event to scroll down in portions, however this doesn't work very well when users need to type in text in input fields.  Any possibly solutions for this?

**Comment by quentinhocde** [comment]
Hi 👋

We just fix this problem on version 3.1.1.
Now if you are focusing on a Input or Textarea element, the spacebar event had no effect on the scroll value.

We also fix the spacebar+shift event to scroll up ✌️

**Comment by Daelen** [comment]
This appears to still be an issue for me. When typing in a textarea the first space doesn't jump you down the page but if you press the spacebar again it jumps.
