### ISSUE TITLE
z Index

### ISSUE THREAD

**Issue by fresheyedart** [locomotivemtl/locomotive-scroll#252]
Hello 👋

I`m sorry if It`s a noob question 😄 
But how can I set z index?
I`m making a hamburger menu and main menu comes from  x -100% and must placed on top of the z index.
But my menu placed bottom of the all contents. It was fine until I use LS. 
Any idea please.

Thank you 👊

**Comment by saidMounaim** [comment]
can you share the code

**Comment by fresheyedart** [comment]
Finally,  I just let my navbar out from data-scroll-container and it worked thanks :)
