### ISSUE TITLE
Doesn't work on mobile?

### ISSUE THREAD

**Issue by remleau** [locomotivemtl/locomotive-scroll#26]
Is it me or its not working on mobile ? https://locomotivemtl.github.io/locomotive-scroll/

**Comment by evromalarkey** [comment]
It would be cool if the parallax effect it's worked with native scroll on mobile, maybe with some extra attribute data-scroll-mobile ?

**Comment by thiagorossener** [comment]
Hey @quentinhocde, great lib!

I'm just having trouble with the smooth mobile option. I cloned the repo, added the `smoothMobile` option to Locomotive demo page, built it and it looks totally broken to me.

Is it a known issue?
