### ISSUE TITLE
Locomotive Scroll x ScrollReveal

### ISSUE THREAD

**Issue by haroldao** [locomotivemtl/locomotive-scroll#263]
Hello 👋 guys.

Is it possible to use [ScrollReveal](https://scrollrevealjs.org/)... Because when I scroll (with L. Scroll & S. Reveal) my elements don't show up.

My thought is since Locomotive Scroll doesn't use native Scroll, Scroll Reveal doesn't know when an element is reached...

Is there any way to make it work?

Thank you 👊

**Comment by maxmmyron** [comment]
Howdy! 👋

If you're still having this issue, LocomotiveScroll comes with built-in "in-view" functions and classes. What you might be trying to achieve with ScrollReveal may already be possible in LocomotiveScroll.

Each element in view is assigned an "is-inview" class with LocomotiveScroll, and you can use that to create scroll-in animations, scroll-out animations, and etc.

There is also an event listener that allows you to call custom functions when an element scrolls into the viewport. You can read the documentation for more information 🔍

**Comment by haroldao** [comment]
> Howdy! 👋
> 
> If you're still having this issue, LocomotiveScroll comes with built-in "in-view" functions and classes. What you might be trying to achieve with ScrollReveal may already be possible in LocomotiveScroll.
> 
> Each element in view is assigned an "is-inview" class with LocomotiveScroll, and you can use that to create scroll-in animations, scroll-out animations, and etc.
> 
> There is also an event listener that allows you to call custom functions when an element scrolls into the viewport. You can read the documentation for more information 🔍

Thank you 🚀🎉
