### ISSUE TITLE
Horizontal Scroll Viewport Conflict

### ISSUE THREAD

**Issue by mohnishlandge** [locomotivemtl/locomotive-scroll#269]
Hello 👋

**Describe the bug**
Horizontal Scroll Viewport Conflict:
While using horizontal scroll website gets stuck in the middle & doesn't scroll all the way to the end of the website.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'locomotive scroll project & add horizontal scroll'
2. Click on 'add container & sections'
3. Scroll down to 'scroll to notice the error'
4. See an error

**Expected behaviour**
The website gets stuck in middle should reach till the end

`

Uncaught TypeError: Cannot read property 'inView' of undefined
    at locomotive-scroll.esm.js:2585
    at NodeList.forEach (<anonymous>)
    at _default.addElements (locomotive-scroll.esm.js:2546)
    at _default.init (locomotive-scroll.esm.js:2121)
    at Smooth.init (locomotive-scroll.esm.js:3074)
    at new Smooth (locomotive-scroll.esm.js:3059)
    at Module../src/script.js (script.js:111)
    at __webpack_require__ (bootstrap:18)
    at startup:3
    at startup:5
`

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [latest]

Thank you 👊

**Comment by saidMounaim** [comment]
Use Horizontal Scroll With GSAP, Check Out This Link

https://codepen.io/cameronknight/pen/qBNvrRQ

**Comment by mohnishlandge** [comment]
thing is it works different on nuxt, perfectly normal.
https://codepen.io/cameronknight/pen/qBNvrRQ thank you for this
