### ISSUE TITLE
Disable Locomotive Scroll for a specific page

### ISSUE THREAD

**Issue by mathieupreaud** [locomotivemtl/locomotive-scroll#274]
Hi,

I'm building a Woocommerce website and I would like to disable Locomotive Scroll on the checkout page.

I tried this code, but it doesn't work. How could I disable Locomotive  for a specific page? My website is not running with Ajax.

   ```
 window.addEventListener("load", function() {
        if ($('.woocommerce-checkout').length) {
          scroll.stop();
          scroll.destroy();
        }
     });
```

Thanks!

**Comment by 19h47** [comment]
Hello @mathieupreaud 👋🏼

I use LocomotiveScroll on a **WooCommerce** website too and I have to disable it on certain pages. 

What I do is adding a data attribute on body and checking it to instantiate or not the `smooth` option ([see](https://github.com/19h47/rider404/blob/main/src/scripts/modules/Scroll.js#L15))

```javascript
const scroll = new LocomotiveScroll({
	smooth: JSON.parse(this.el.getAttribute('data-scroll-smooth')),
});
```
Hope it helps

**Comment by mathieupreaud** [comment]
Hi @19h47 

Thanks your help. However I'm not 100% sure to understand. How do you add the attribute `data-scroll-smooth` to `body`? With conditional PHP code in relation with your template page?

**Comment by 19h47** [comment]
Totally @mathieupreaud! You can override a template or maybe hook into `body_class` (this one is not very clean in my opinion) to add some attribute on body tag.

In my case I use a template that call the `woocommerce_checkout ` shortcode. In this template I pass a variable `scroll_smooth` to false ([see](https://github.com/19h47/rider404/blob/main/templates/checkout-page.php#L16)).
And then in my index I test the `scroll_smooth` variable ([see](https://github.com/19h47/rider404/blob/main/views/index.html.twig#L32)).

I use Timber, but you can apply the same logic with PHP.

**Comment by mathieupreaud** [comment]
Thank you very much @19h47, it works perfectly!
