### ISSUE TITLE
Opening page in new tab with anchor causes page to cut off at the top

### ISSUE THREAD

**Issue by Eldzej** [locomotivemtl/locomotive-scroll#275]
Locomotive version: 4.1.1 (tried downgrading as well)

I have a page with several anchors (id) in it, and accessing them from another page (link has target="_blank", so it opens in new tab).
Problem is that Locomotive apparently thinks the page starts at the anchor element, and cuts off everything above it (and creates a blanks space below).

I tried all the workarounds mentioned in another issues here (width: 100vw / height: 100vh on html and body, dispatching resize even on timeout), but nothing seems to be working.

Weirdly enough, it happens only when opening the page through a link. When I open the page by typing the URL, it works fine, and only in Chromium/WebKit browsers (firefox seems to work fine)

Cut off at top
![Cut off at top](https://user-images.githubusercontent.com/22633986/114847523-1412a980-9dde-11eb-993d-25e5d389858f.png)

Blank space at the end
![Blank space at the end](https://user-images.githubusercontent.com/22633986/114847336-e4fc3800-9ddd-11eb-825f-34277fe20eb5.png)

**Comment by Eldzej** [comment]
I think I managed to fix this, was some weird conflict between Locomotive and page transition library that fought over who gets to scroll to anchor...

**Comment by cojaco** [comment]
I had a similar problem that lms cuts off the page when a hash was in the URL, I think it has something to-do with native browser behavior to jump to the place, when lms kicks in and gets disturbt.

So I try to prevent the native browser Jump.

The best way I could do this was setting a global variable after lms init
window.lmsInit = true;

and have this script in my head above all other stuff

```
<script>
        if (window.location.hash) [{](url)
            window.scrollTo(0, 0);         // execute it straight away
            checkForLMS();
            function checkForLMS() {
                if(!window.lmsInit) {
                    setTimeout(function() {
                        window.scrollTo(0, 0);
                        checkForLMS()// run it a bit later also for browser compatibility
                    }, 10);
                }
            }
        }
</script>
```
