### ISSUE TITLE
How to recreate this effect from one of your websites

### ISSUE THREAD

**Issue by dejan-77** [locomotivemtl/locomotive-scroll#28]
Hi mate,
total newbie here. I am designer with little coding skills, but I like to stick my nose into things i don't understand and try to learn from mistakes. 
I was able to run the script and know how to set up a few basic functions. everything works perfectly. i would love to know how to do something i saw on the web site that you make: carbonbeauty.com 
the big title "Carbon Beauty...." goes horizontally to the left, but doesn't go up as I scroll. Is it possible to recreate something like that and how?
I hope you will help me as I have been stuck for a long time in solving this problem, though I would love to learn a lot more. For example, how to use data-scroll-sticky and other things. 
it might not be a bad idea to do some more detailed documentation with more examples for people with learning difficulties like me.
Totally love your work, and thank you for sharing this amazing script with us, really appreciate it. :)
Cheers

**Comment by dejan-77** [comment]
Thanks anyway

**Comment by lvidal1** [comment]
@dejan-77 did you resolve it?

**Comment by dejan-77** [comment]
@lvidal1 unfortunately not... they never answer 😏
