### ISSUE TITLE
How to set time duration to scrollTo method?

### ISSUE THREAD

**Issue by alexander-gush** [locomotivemtl/locomotive-scroll#29]
Hi,
Is it possible to set time duration to scroolTo?

**Comment by Jerek0** [comment]
At the moment you cannot set a duration in `scrollTo`. We'll keep this in mind and see if it can be an option on future releases.

**Comment by jarovision** [comment]
pleeeease please add this.. it would be such a game changer! 🥇

**Comment by podrivo** [comment]
This will be greatly appreciated!
As I'm working in very long page, which is around 30k pixels in height, with a "go to top button" at the bottom, the default behavior takes some time to fully scroll to the top. If I could change `speed` maybe would help.

**Comment by mehdilouraoui** [comment]
Hello there! no update planned with this feature?

**Comment by splurtcake** [comment]
+1

**Comment by thomas-dm** [comment]
When it comes to new features, I feel like this should be a **top priority**. The addition of a callback would be nice as well. As it stands today, the lack of _any_ way to control the programmatic scroll is a real hassle.

**Comment by Jerek0** [comment]
Hi! 
We refactored the `scrollTo` system and added `duration` and `easing` parameters. 🙂
Please refer to the documentation here: https://github.com/locomotivemtl/locomotive-scroll#instance-options

**Comment by francescocortese** [comment]
How to edit the speed of scrollTo? This is my code, some could help me? Thanks. :)
```
const locoScroll = new LocomotiveScroll({
  el: document.querySelector('.scroll_container'),
  smooth: true,
  lerp: 0.05,
  smoothMobile: false
});
```
