### ISSUE TITLE
You can't scroll horizontally on touchpad in DevTools (Chrome/Firefox)

### ISSUE THREAD

**Issue by Iraklikandelaki** [locomotivemtl/locomotive-scroll#292]
If you swipe vertically, it works fine. Even though the direction is horizontal, if you swipe vertically, it swipes to the right/left, but the horizontal movement simply doesn't trigger anything at all.

**Comment by RamziBach** [comment]
`
const scroll = new LocomotiveScroll({
  el: document.querySelector('[data-scroll-container]'),
  smooth: true,
  gestureDirection: 'both',
  tablet: {
    smooth: true,
    direction: 'horizontal',
    gestureDirection: 'horizontal'
  },
  smartphone: {
    smooth: true,
    direction: 'horizontal',
    gestureDirection: 'horizontal'
  }
})
`

**Comment by Iraklikandelaki** [comment]
@RamziBach Nah, that's not it. 
It works as expected with an actual touch device but is messed up in DevTools touch.
