### ISSUE TITLE
Playing videos makes page laggy as hell

### ISSUE THREAD

**Issue by Iraklikandelaki** [locomotivemtl/locomotive-scroll#296]
https://codepen.io/SaltyMedStudent/pen/abJdqKO?editors=1010
Scroll to the dolphin video and play it, scroll the page while the video is playing, see the results yourself.

Update: Fine on Mozilla, laggy on Chrome.

**Comment by Jerek0** [comment]
Hi, sorry to hear that but I don't see any lagging issues on my end with Chrome and my config is not high end. 
Make sure your computer is not under heavy load with other programs.
