### ISSUE TITLE
Firefox Multiplier not working on Windows

### ISSUE THREAD

**Issue by Nomnomburger** [locomotivemtl/locomotive-scroll#299]
Hello 👋

**Describe the bug**
I am trying to use `firefoxMultiplier` to boost speed but it is not changing anything on the Windows version of firefox.

**To Reproduce**
1. Add `firefoxMultiplier: 100` to the js file
2. Open on firefox
3. Scroll down
4. See error (not boosting speed)

**Expected behavior**
The code should boost the speed of scrolling on Firefox windows

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 88.0.1

Thank you 👊

**Comment by Xonn** [comment]
I don't think it's OS related, i've got the same problem on MacOS.

- MacOS Big Sur 11.4
- Firefox 89.0

**Comment by Dushyant1295** [comment]
For me too  used firefoxMultiplier to boost speed but  nothing Happend

**Comment by pangramweb** [comment]
> I think I've to disable locomotive scroll on Firefox

Hi, what would be the code to do that ?

**Comment by fcisio** [comment]
I had a similar issue #218 
You can take a look at the fix

**Comment by Iraklikandelaki** [comment]
This is how I fixed this: 

` multiplier: navigator.userAgent.toLowerCase().indexOf('firefox') > -1  ? 1  : 0.8,`

**Comment by Nomnomburger** [comment]
Just an update, I believe Firefox multiplier is now working properly, at least in my usage. Closing issue!
