### ISSUE TITLE
Sticky elements don't stay inside parent after resizing the browser

### ISSUE THREAD

**Issue by patchampoux** [locomotivemtl/locomotive-scroll#30]
Hi there,

First of all, awesome stuff, I love it. I just found a little bug that is pretty annoying. When an element is set to sticky, if you scroll past it's wrapper and then you resize your browser, it's positioning gets all funky and it starts to stay sticked beyond it's wrapper dimensions. The bug is present on your demo page too. Scroll past the 04 Fixed elements section then open the console (or just resize your browser) and you'll see what I mean.

![image](https://user-images.githubusercontent.com/7132345/64218747-f7d42a00-ce90-11e9-8b3e-ec0a08193cc8.png)

Thank you!

**Comment by JamesHRowe** [comment]
Any update on this? Having the exact same issue where resizing causes the layout to break and as shown above this unfortunately happens in the main demo also.

**Comment by mirkosaugo** [comment]
Same problem in my website, any update on this?

**Comment by dimative** [comment]
Same problem ... Any news?

**Comment by kasparsz** [comment]
I had the same issue, problem seems to be in [scripts/Smooth.js](https://github.com/locomotivemtl/locomotive-scroll/blob/master/src/scripts/Smooth.js#L362) line 362.
In calculation for elements sticky position "bottom" is being used distance to the element,  which seems weird to me. If I remove "elDistance" from the calculation, then sticky elements work correctly after resizing browser too.

It was added in https://github.com/locomotivemtl/locomotive-scroll/commit/29d07a8af14e4d9f81212a79e0ec208dbe93d451
but commit description doesn't have any references to tickets, so I have no idea what was the issue. 
@antoineboulanger Do you remember what was the issue it was trying to fix, was it some edge case? I couldn't find any ticket from that date

**Comment by auriga-z** [comment]
It's fixed it the latest version [3.3.9](https://github.com/locomotivemtl/locomotive-scroll/releases/tag/3.3.9)

**Comment by ZachSaucier** [comment]
@auriga-z It doesn't seem to be fixed on the Locomotive site or the site I'm building.

**Comment by auriga-z** [comment]
@ZachSaucier Try putting this code

const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true
});

Inside a window.onload, It fixed the bug for me.

**Comment by ZachSaucier** [comment]
I'm already doing that @auriga-z. Issue still persists.

**Comment by mrlss** [comment]
Hey guys, @Jerek0 @quentinhocde could you take a look into this request https://github.com/locomotivemtl/locomotive-scroll/pull/108 - it fixes this issue. Thanks.

**Comment by dayneh88** [comment]
This bug is still present. I'm checking `src/scripts/smooth.js` and none of the updates from the supposed commit that fixed it is present. Any updates on this?

**Comment by JuchokJuk** [comment]
Hey guys, I was able to fix this bug by simply adding a wrapper around the sticky element. Looks like **data-scroll-section cannot be the immediate parent of a sticky element**.

_before:_
<div id="sticky" data-scroll-section>
  <div data-scroll data-scroll-sticky data-scroll-target="#sticky">
   sticky block stops being sticky on resize
  </div>
</div>

_after:_
<div data-scroll-section>
  <div id="sticky">
    <div data-scroll data-scroll-sticky data-scroll-target="#sticky">
      sticky block works fine
    </div>
  </div>
</div>
