### ISSUE TITLE
Rotate Transform

### ISSUE THREAD

**Issue by mikeimpart** [locomotivemtl/locomotive-scroll#32]
Hi, thanks for this great plugin first of all. It works great.

I wanted to see if it was possible to add a rotate transform based on the scroll position? For example, if I apply **data-scroll-speed** to an element, can I rotate it as well? Similar to what you do with the "video reel" button on this site: https://mathieulevesque.com/en

Thanks

**Comment by quentinhocde** [comment]
Hi!

It's not possible with a data-attribute because to many things could be updated by the scroll value (like the opacity, different types of transform).
You can simply use the on `scroll` event and update the style of your element with the scroll value like this :

```
scroll.on('scroll', (instance) => {
    console.log(instance.scroll.y);
});
```

Thanks :)

**Comment by Iraklikandelaki** [comment]
Allow me to chime in, for completely new people to locomotiveScroll, let me finish the example:

let clouds = document.querySelector(".clouds");

scroller.on("scroll", (instance) => {
  if (instance.scroll.y > 1200) {
    clouds.style.transform = "rotate(90deg)";
  } else {
    clouds.style.transform = "rotate(0deg)";
  }
});

You can manipulate anything with that (adding/removing classes, changing styles and etc), you need to determine the scroll position on y axis first via console.log using the example above.
