### ISSUE TITLE
After window resize  ,  if you hit refresh , scrolls  not working

### ISSUE THREAD

**Issue by prakash03yes** [locomotivemtl/locomotive-scroll#322]
After resizing the window , if you hit refresh , its completely not working! I also tested it in [https://locomotivemtl.github.io/locomotive-scroll]   please share any suggestion. 

Thankyou!

**Comment by Iraklikandelaki** [comment]
Can't really replicate the issue, can you record your screen or something?

**Comment by prakash03yes** [comment]
https://user-images.githubusercontent.com/77315058/128391423-8bceee0a-5892-4d8e-bd8b-01bc682ed019.mp4

it doesn't support of some screens ? or any other cases ??? I looked at the documentation , couldn't find anything helpful,

**Comment by Iraklikandelaki** [comment]
That's super weird actually, I tried following the steps in the video and couldn't get the same outcome as you did.
Why is that an issue to a regular user anyway? I mean if you try to mess things up manually from DevTools, you could simply delete the HTML elements and you would be good.
Is there any case where this affects the performance?

**Comment by prakash03yes** [comment]
Hey ...!!! I developed my portfolio website using Smooth Scroll , locomotive-scroll is really awesome , but when i try to adjust things for mobile & tablet , i don't know why after resizing the window  the smooth scroll is not working , so i tested the same in the demo site , i found the same problem there too ( you have seen the video right! )... but after sometime i found the solution.. 
the below code works for me ... I was curious get different answers... fine you are awesome , Thanks for your valuable time... 
![image](https://user-images.githubusercontent.com/77315058/128446912-6ac46d87-3c79-4616-9c0c-a99ffee2f82f.png)

**Comment by Pranaymajee** [comment]
My scrollbar is still showing in mobile view. any solution for how to prevent that ?

**Comment by prakash03yes** [comment]
can you share , photo or video of your problem !!
