### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by Mishkamshka** [locomotivemtl/locomotive-scroll#339]
Hi, is there a way I can add an anchor from one page to another?

When I do the entire page is ruined.

**Comment by saidMounaim** [comment]
Check this, 
` if (window.location.hash) {
   var hash = window.location.hash.substring(1); 
   const target = document.getElementById(hash);
   scroll.scrollTo(target);
 } `

**Comment by contiele** [comment]
Hi, i solved it like this,
$(window).on("load", function() {
     locoScroll.init();
  });
