### ISSUE TITLE
Cannot install npm package

### ISSUE THREAD

**Issue by barbudour** [locomotivemtl/locomotive-scroll#34]
Hi, I am trying to install `locomotive-scroll` via npm, but getting this error, what could be the problem?

> air-ivan:xtremity.new vinokurov$ npm i --save locomotive-scroll
> npm WARN ninelines-template@2.6.1 No repository field.
> 
> npm ERR! code EPERM
> npm ERR! syscall spawn
> npm ERR! errno EPERM
> npm ERR! Error: spawn EPERM
> npm ERR!     at ChildProcess.spawn (internal/child_process.js:366:11)
> npm ERR!     at spawn (child_process.js:538:9)
> npm ERR!     at execFile (child_process.js:221:15)
> npm ERR!     at tryCatcher (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> npm ERR!     at ret (eval at makeNodePromisifiedEval (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
> npm ERR!     at promiseRetry (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
> npm ERR!     at /Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
> npm ERR!  { Error: spawn EPERM
> npm ERR!     at ChildProcess.spawn (internal/child_process.js:366:11)
> npm ERR!     at spawn (child_process.js:538:9)
> npm ERR!     at execFile (child_process.js:221:15)
> npm ERR!     at tryCatcher (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> npm ERR!     at ret (eval at makeNodePromisifiedEval (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
> npm ERR!     at promiseRetry (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
> npm ERR!     at /Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
> npm ERR!   cause:
> npm ERR!    { Error: spawn EPERM
> npm ERR!        at ChildProcess.spawn (internal/child_process.js:366:11)
> npm ERR!        at spawn (child_process.js:538:9)
> npm ERR!        at execFile (child_process.js:221:15)
> npm ERR!        at tryCatcher (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> npm ERR!        at ret (eval at makeNodePromisifiedEval (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
> npm ERR!        at promiseRetry (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
> npm ERR!        at /Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 errno: 'EPERM', code: 'EPERM', syscall: 'spawn' },
> npm ERR!   stack:
> npm ERR!    'Error: spawn EPERM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at spawn (child_process.js:538:9)\n    at execFile (child_process.js:221:15)\n    at tryCatcher (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)\n    at ret (eval at makeNodePromisifiedEval (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)\n    at promiseRetry (/Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)\n    at /Users/vinokurov/.npm-global/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24',
> npm ERR!   errno: 'EPERM',
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'spawn',
> npm ERR!   parent: 'xtremity.new' }
> npm ERR!
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It is likely you do not have the permissions to access this file as the current user
> npm ERR!
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/vinokurov/.npm/_logs/2019-09-16T00_10_18_408Z-debug.log
> air-ivan:xtremity.new vinokurov$

**Comment by ammein** [comment]
Famous `EPERM` issue. Means permission issue running from command line. This problem is well known on Windows OS platform. Just running the command on Terminal with Administrator

**Comment by barbudour** [comment]
> Famous `EPERM` issue. Means permission issue running from command line. This problem is well known on Windows OS platform. Just running the command on Terminal with Administrator

Thanks, earned with "sudo npm i --save locomotive-scroll"
