### ISSUE TITLE
Scroll after use ScrollTo methods dont work

### ISSUE THREAD

**Issue by lucrampro** [locomotivemtl/locomotive-scroll#343]
Hello all👋

I have a probleme, after i use scrollTo methods when i scroll with my mouse the website bug glitch, i can see first block of my website and glitch to normal position

**To Reproduce**

1. Use `scrollTo` methods callback to CTA ln your website 
2. Click on the CTA
3. Scroll top

**Screenshots**
i dont have screenshot but i can give to you a link for test (https://signature-onapegape.netlify.app/), follow rules to Reproduce but use "savoire-faire" or "contact" CTA in header of my website for callback ScrollTo methods

**Desktop**
 - OS: [windows / mac]
 - Browser [chrome]
 - Version [80 ?]

Thank you and im sorry for my bad english langage 👊

**Comment by saidMounaim** [comment]
You can use "data-scroll-to"

`<a href="#savoir-faire" data-scroll-to>savoir-faire</a>

<section data-scroll-section data-scroll-section-id="savoir-faire">
`

**Comment by saidMounaim** [comment]
You can use "data-scroll-to"

`<a href="#savoir-faire" data-scroll-to>savoir-faire</a>

<section data-scroll-section data-scroll-section-id="savoir-faire">`

**Comment by saidMounaim** [comment]
You can use "data-scroll-to"

```
<a href="#savoir-faire" data-scroll-to>savoir-faire</a>
<section data-scroll-section data-scroll-section-id="savoir-faire">
```

**Comment by lucrampro** [comment]
Thanks @saidMounaim for your reply this is ok for me, i have normal behavior with your solution ! thanks a lot
