### ISSUE TITLE
Events are called even when an element is not in view

### ISSUE THREAD

**Issue by timothyachumba** [locomotivemtl/locomotive-scroll#372]
Hello 👋

**Describe the bug**
When I set data-scroll-repeat to true an event is called on that element even when its not in view.

**Expected behavior**
Event should only be called once the element is in view and then back in view if I scroll back to  it.

Thank you 👊

**Comment by saidMounaim** [comment]
to do that use `data-scroll-class `, check out docs

**Comment by timothyachumba** [comment]
found a fix

**Comment by richardcalahan** [comment]
What was the fix?

**Comment by timothyachumba** [comment]
The issue only happened when I had two elements both be in-view at the same time but once. It was a combination of my so-so javascript and implementation. Nothing wrong with Locomotive.
