### ISSUE TITLE
Elements are pop in when scrolling up

### ISSUE THREAD

**Issue by timothyachumba** [locomotivemtl/locomotive-scroll#376]
It looks like things are repainting when scrolling up. Is there a class I can add to solve this issue?

![CleanShot 2021-12-01 at 12 46 45 2](https://user-images.githubusercontent.com/2601332/144237245-5b642398-d18d-4691-9b30-4056dfe895f6.gif)

**Comment by Da-Black-Man** [comment]
@timothyachumba try updating has-scroll-smooth class with the following
```

&.has-scroll-smooth {
        overflow: hidden;
        position: fixed;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;  
    }
```

**Comment by timothyachumba** [comment]
Worked like a charm! Thanks
