### ISSUE TITLE
Allow scroll on "fixed" overlay elements

### ISSUE THREAD

**Issue by benjaminrobinet** [locomotivemtl/locomotive-scroll#397]
I have a fixed element on my page, but when scrolling with the mouse on this element, I guess the "mousewheel" event is canceled / not interpreted. I guess it is the expected behavior for most of the case, but I would like to still be able to scroll, even if hovering this element (as in fact it's a background overlay). Any idea on how to do that ?

**Comment by oguilleux** [comment]
You should create a new locomotive scroll instance for that overlay. 

Here is an example : https://agentandartists.com - content is scrollable and menu (overlay) is scrollable.

**Comment by benjaminrobinet** [comment]
@oguilleux That's not what I meant, I was probably not clear enough. I did a litter Codesandbox to explain my case: https://codesandbox.io/s/locomotive-scroll-allow-forward-from-overlay-element-o84rr0?file=/src/index.js

As the red element here is fixed on a top layer, when I scroll on it, the [data-scroll-container] do not scroll. I mean, is there a way to "forward" the events on another instance. Like creating two instances, but telling one to control the other one.

Thank you for your reply !

**Comment by oguilleux** [comment]
oh ok just add : `scrollFromAnywhere: true` in your parameters 😁

**Comment by benjaminrobinet** [comment]
Well... Thanks @oguilleux 🤡
