### ISSUE TITLE
.forEach() on NodeLists unsupported on IE11

### ISSUE THREAD

**Issue by mats852** [locomotivemtl/locomotive-scroll#40]
Wrapping every Nodelists with `Array.from()` would fix IE11 compatibility.

**Comment by antoineboulanger** [comment]
Hi, for IE11 support, you need polyfills. I added an example in the [readme](https://github.com/locomotivemtl/locomotive-scroll#browser-support). 
We don't want to write our codebase in ES5 for IE11. Thanks.
