### ISSUE TITLE
A problem with uploading my webpage to a server.

### ISSUE THREAD

**Issue by SilverSomma** [locomotivemtl/locomotive-scroll#409]
Hello.

Right now I have added locomotive-scroll to my webpage (index.js) as it is said in the tutorial:

`import LocomotiveScroll from "locomotive-scroll";

  const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true,
    tablet: {smooth: true},
    smartphone: {smooth: true},
    })`

I have used Parcel compiler to compile and create a local host when writing the code. Everything has worked fine with no errors. When I upload the webpage files with FTP to an server and run the files, locomotive-scroll and JS funsctions are not working. I get an error:

Uncaught TypeError: Failed to resolve module specifier "locomotive-scroll". Relative references must start with either "/", "./", or "../".

Would be thankful for any kind of help or guidance.
![HTML](https://user-images.githubusercontent.com/94069570/159013044-80e900f7-d411-42bc-9ea0-3a93b8eb2d73.png)
![indexJS](https://user-images.githubusercontent.com/94069570/159013049-ab967613-cba7-45eb-bdbc-2d9e87e2c503.png)

**Comment by thedavidthomas** [comment]
Hi @SilverSomma,

What is in the `dist` folder? I think the contents of this is what needs uploading to the server as its would typically contain the final compiled production ready version.

you may also need to run the `parcel build` command to make this version.

**Comment by SilverSomma** [comment]
Yes, I uploaded everything including the `dist` folder. 

But I managed to get everything working by specifing the file path for the `locomotive-scroll` import line. I needed to use an server provider URL for the file destination in the server.

**Comment by ToumiAbdelkader** [comment]
Hi, just asking if you found a solution to this problem? face in it rn

**Comment by yann0851** [comment]
Hy what is you're solution, I have the same problem

**Comment by SrGexj** [comment]
@SilverSomma Did you found a solution?? I'm trying  to fix it but there's not info about this type of problem on locomotive page or github post/s.

**Comment by yesm4n** [comment]
<script type="./module" src="app.js"></script>

Writing your module like this should work. I just encountered the same problem @FourSol  @SrGexj
