### ISSUE TITLE
Mouse tracking

### ISSUE THREAD

**Issue by cyrillebrotto** [locomotivemtl/locomotive-scroll#414]
Hello Here's the problem : In my locomotive scroll page, I have a mouse tracking like this :
https://codepen.io/aleseect/pen/bGRNbRj

it works well when I'm not scrolling.

I would like to understand why the green circle no longer follows the mouse when I scroll.
When I scroll, it does not stay around the mouse. it goes up all the more as I go down in the page.

you can see here : https://cyrillebrotto.com/test/

Thank you for your answers

**Comment by Dushyant1295** [comment]
Hi @cyrillebrotto   have a look at this library  https://github.com/Dushyant1295/dpkCursor
it works well with locomotive scroll
ie.  https://the-revolvers.com/

**Comment by cyrillebrotto** [comment]
I'll look :-)
Thank you

**Comment by cyrillebrotto** [comment]
It works well
Thank you
