### ISSUE TITLE
how to get `data-scroll-call` to work?

### ISSUE THREAD

**Issue by adamcoulombe** [locomotivemtl/locomotive-scroll#42]
I'm not having any luck getting any callbacks to work, anyone have any luck with this?

`<div data-scroll-call="someIdentifier"><div>`

```
scroll.on('call',(func)=>{
      console.log(func);   //nothing happens!
 })
```

**Comment by friconelli** [comment]
Try to add the "data-scroll" attribute to initialize the element, like this:
`<div data-scroll data-scroll-call="someIdentifier"><div>`

**Comment by adamcoulombe** [comment]
Ah! amazing. Thanks @friconelli , thats all it was!
