### ISSUE TITLE
Scrollbar thumb height is not proper

### ISSUE THREAD

**Issue by abrupareliya02** [locomotivemtl/locomotive-scroll#429]
Hello 👋

Here is the script which I am using for locomotive-scroll:
let scrollContainer = document.querySelector("[data-scroll-container]"); 
var scroll; 
scroll = new LocomotiveScroll({ el: scrollContainer, smooth: true, });

c-scrollbar-thumb height is 8048px. My main viewport height of data-scroll-container is 15804px.

HTML structure is like:
<main data-scroll-container>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
    <section data-scroll-section></section>
</main>

Thank you 👊
![Screen Shot 2022-05-18 at 1 29 44 PM](https://user-images.githubusercontent.com/82654319/168989729-4256cf5a-9d38-44e2-9fc1-53ce0b4d402e.png)

**Comment by Toyoudo** [comment]
@abrupareliya02  hope it will help you #432

**Comment by get-web** [comment]
Try removing position: relative; from body

**Comment by abrupareliya02** [comment]
Working fine now. Thanks @get-web
