### ISSUE TITLE
It doesn't work on my Android mobile

### ISSUE THREAD

**Issue by cyrillebrotto** [locomotivemtl/locomotive-scroll#440]
Hello I tested this code.
[https://codepen.io/Cyrille-Brotto/pen/zYRVoBa](https://codepen.io/Cyrille-Brotto/pen/zYRVoBa)
It works well on firefox and chrom on desktop. It doesn't work on my Android mobile.
Do you have an idea?
Thank you

**Comment by mmilde** [comment]
I had the same problem, but now it works on all mobile.
Maybe you should try with this setup:
```
window.addEventListener("load", () => {
const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true,
    scrollFromAnywhere: true,
    multiplier: 1,
    getDirection: true,
    reloadOnContextChange: true,
    touchMultiplier: 3,
    smoothMobile: 0,
    smartphone: {
        smooth: !0,
        breakpoint: 766
    },
    tablet: {
        smooth: !0,
        breakpoint: 1010
    },
});
```

**Comment by cyrillebrotto** [comment]
I added some data-scroll and datascroll-section.
I changed smoothMobile to true.
Now it works on desktop and mobile :-)
Thank you very much
