### ISSUE TITLE
How to init plugin ?

### ISSUE THREAD

**Issue by Venegrad** [locomotivemtl/locomotive-scroll#447]
Im using webpack es6;

```
import LocomotiveScroll from 'locomotive-scroll';
const scroll = new LocomotiveScroll();
```

init after dom ready, and adding in html data-scroll data-.... etc.
```
nothing happend
```
console.log(scroll) is aviable, but nothing work, what im do wrong?

**Comment by Venegrad** [comment]
maybe i need specialy register some option? or im something missing?

**Comment by saidMounaim** [comment]
yeaah u have to register some options

`const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true
})`

**Comment by Venegrad** [comment]
> yeaah u have to register some options
> 
> `const scroll = new LocomotiveScroll({ el: document.querySelector('[data-scroll-container]'), smooth: true })`

If I do this, the whole container just becomes fixed and the elements inside still don't move either.

**Comment by Venegrad** [comment]
> yeaah u have to register some options
> 
> `const scroll = new LocomotiveScroll({ el: document.querySelector('[data-scroll-container]'), smooth: true })`

Thank u!
