### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by claudioontheweb** [locomotivemtl/locomotive-scroll#46]
I get the following error when using locomotive-js as described in the Readme:

``Uncaught SyntaxError: Cannot use import statement outside a module``

My HTML:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Locomotive Test</title>
  </head>
  <body>
    <div id="js-scroll">
      <h1 data-scroll>Welcome</h1>
    </div>
    <script src="js/main.js"></script>
  </body>
</html>
```

And the JS:
```
import LocomotiveScroll from "locomotive-scroll";

const scroll = new LocomotiveScroll({
  el: document.querySelector("#js-scroll"),
  smooth: true,
  getSpeed: true,
  getDirection: true
});
```

**Comment by adamcoulombe** [comment]
are you using webpack/babel? The import statement is ES6 so you need a compiler to build your main.js file

**Comment by claudioontheweb** [comment]
> are you using webpack/babel? The import statement is ES6 so you need a compiler to build your main.js file

How could I miss that... This was it! Thank you 👍

**Comment by thomasinho537** [comment]
Hello, i have same problem but i dont know how to fix it, i tried everything.. can you help me please?

**Comment by thomasinho537** [comment]
i dont know what i have to do with es6
