### ISSUE TITLE
on("call") inconsistency between Native and Smooth scroll

### ISSUE THREAD

**Issue by ebhoren** [locomotivemtl/locomotive-scroll#48]
When listening to "call" event on a LocomotiveScroll instance, you expect to receive 3 params in the callback (value, way, obj).

If you use smooth scrolling, the "call" callback will receive a obj param. This object has a ID property. But if you use native scroll, this object doesn't have a ID property.

Can you add a ID property in Native.js -> addElements for each elements added to the scroll component?
Thanks :)

**Comment by quentinhocde** [comment]
Hi!
It should be fixed with the last commit :)

Thanks
