### ISSUE TITLE
WebpackError: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by edoardolunardi** [locomotivemtl/locomotive-scroll#49]
Hi! 
First of all, thank you for this neat library.

I'm using it with gatsby. I'm instantiating it in useEffect like this

```js
const scroll = new LocomotiveScroll({
      el: scrollRef.current,
      smooth: true,
      smoothMobile: true,
    })
```

Then I create the ref 
```js
const scrollRef = useRef(null)
```
 and assign it to my container
 ```js
<div ref={scrollRef}></div>
```

So far so good, it works in development mode in gatsby (so `gatsby develop`).
The problem arises when I go to production, so with `gatsby build`.

```js
WebpackError: ReferenceError: document is not defined
```

```js
  - locomotive-scroll.esm.js:151 Module../node_modules/locomotive-scroll/dist/locomotive-scroll.esm.js
    node_modules/locomotive-scroll/dist/locomotive-scroll.esm.js:151:1
  
  - index.js:1 Module../src/pages/index.js
    src/pages/index.js:1:1
  
  - interopRequireDefault.js:7 Object.Module._extensions..js
    node_modules/@babel/runtime/helpers/interopRequireDefault.js:7:1
```

Any thoughts? Thank you!

Cheers.

Edit: I've found [this](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules), but It's not working, and [this](https://www.gatsbyjs.org/docs/using-client-side-only-packages/#workaround-3-load-client-side-dependent-components-with-react-loadablel), but I'm not sure how to make it working with locomotive

**Comment by edoardolunardi** [comment]
Solved! After tried many times with the links I posted, I've found a more easy way: basically when the component is mounted, import the module/library. This will fix the problem relate to ssr - see [here](https://www.gatsbyjs.org/docs/debugging-html-builds/)

So

```js
useEffect(() => {
    import("locomotive-scroll").then(locomotiveModule => {
      const scroll = new locomotiveModule.default({
        el: scrollRef.current,
        smooth: true,
        smoothMobile: false,
      })
    })
  }, [])
```

**Comment by ajayns** [comment]
@edoardolunardi This seems to work for imports but did you face any issues with scroll height set by locomotive-scroll? It seems to always mess up when used witth Gatsby

**Comment by edoardolunardi** [comment]
@ajayns Hi, I used locomotive some months ago just for fun, the import thing worked and I don't think I've ever faced such a problem with the scroll height as far as I can remember...

**Comment by ajayns** [comment]
@edoardolunardi Oh alright, thank you!

**Comment by ryanturnerwebdev** [comment]
FYI if you want to fix the build issue without having to load the script asynchronously, add this to gatsby-node.js

``` js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html" || stage === "develop-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /locomotive-scroll/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```
