### ISSUE TITLE
Locomotive Scroll Image Parallax Effect is Flickering

### ISSUE THREAD

**Issue by officialgio** [locomotivemtl/locomotive-scroll#496]
Hello 👋

**Describe the bug**
parallax effect is not working on the Parallax section. Notice that it flicks when the section shows up which is not what I want.

**Expected behavior**
It should have a smooth parallax effect for the experience section. 

**Pen**
https://codepen.io/officialgio/pen/GRYRBvb

Try adding an image and that flickering happens even more instantly. Such as this:

`.experience img  {
    position: absolute;
    width: 100%;
    height: 100%;
    z-index: 1;
}`

**Comment by shivammakwan** [comment]
Did you found any solution for this?
