### ISSUE TITLE
How i can use scrollTo?

### ISSUE THREAD

**Issue by strilezkijslawa** [locomotivemtl/locomotive-scroll#5]
Can i use scrollTo function for "scroll to top"? And how?

**Comment by quentinhocde** [comment]
Hi!

Yes, in the `scrollTo()` function you have options (toTop, toBottom). You just need to set toTop value to true when you trigger the scroll event.

Like this example (.js-scroll is the scroll container) : 
~~~
$('.js-scroll').triggerHandler({
    type: 'scrollTo.LocomotiveScroll',
    options: {
        toTop: true
    }
})
~~~

**Comment by strilezkijslawa** [comment]
Thanks!
