### ISSUE TITLE
Locomotive v5 ReferenceError: window is not defined

### ISSUE THREAD

**Issue by tariknh** [locomotivemtl/locomotive-scroll#506]
Hello 👋

**Describe the bug**
When using locomotive v5, npm run dev works but on build it fails with "ReferenceError: window is not defined"

**To Reproduce**
1. Add new locomotive scroll to UseEffect
2. npm run build/dev
3. See error: ReferenceError: window is not defined

**Expected behavior**
Window to be defined when its called in useEffect

Thank you 👊

**Comment by Lunari8546** [comment]
I found a solution in [this issue](https://github.com/locomotivemtl/locomotive-scroll/issues/49), basically you need to import the module after the component mounted. In your case, you need to import it in `UseEffect()`.

**Comment by ondrejjcizek** [comment]
SVELTEKIT

**locomotive.ts**
import LocomotiveScroll from 'locomotive-scroll';

// function onScroll({ scroll, limit, velocity, direction, progress }) {
// 	console.log('SCROLL ' + scroll);
// 	console.log('LIMIT ' + limit);
// 	console.log('VELOCITY ' + velocity);
// 	console.log('DIRECTION ' + direction);
// 	console.log('PROGRESS ' + progress);
// }

export function locomotive() {
	const locomotiveScroll = new LocomotiveScroll({
		lenisOptions: {
			wrapper: window,
			content: document.documentElement,
			lerp: 0.1,
			duration: 0.6,
			orientation: 'vertical',
			gestureOrientation: 'vertical',
			smoothWheel: true,
			smoothTouch: true,
			wheelMultiplier: 1,
			touchMultiplier: 0.5,
			normalizeWheel: true,
			easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t))
		}
		// scrollCallback: onScroll
	});
}

**+page.svelte**
<script lang="ts">
	import { onMount } from 'svelte';
	import Horizontal from '../../components/horizontal.svelte';

	onMount(async () => {
		const locomotive = await import('../../imports/locomotive');
		const scroll = locomotive.locomotive();
	});
</script>

**Comment by tariknh** [comment]
Solution for NextJS/React was this

```
useEffect(() => {
    let scroll: import("locomotive-scroll");
    import("locomotive-scroll").then((locomotiveModule) => {
      scroll = new locomotiveModule.default();
    });

   // cleanup phase
    return () => {
      if (scroll) scroll.destroy();
    };
  });
```


If you want more settings you can do it inside like this:
```
useEffect(() => {
        let scroll: import("locomotive-scroll");
        import("locomotive-scroll").then((locomotiveModule) => {
            scroll = new locomotiveModule.default({
                el: document.querySelector("[data-scroll-container]"),
                smooth: true,
                smoothMobile: false,
                resetNativeScroll: true
            });
        });

        // cleanup phase
        return () => {
            if (scroll) scroll.destroy();
        }
    });
```
