### ISSUE TITLE
Lack of Feature Dems 

### ISSUE THREAD

**Issue by asifnaqvi** [locomotivemtl/locomotive-scroll#509]
As much as I want to use it, I find it rather complicated to get my head around many aspects of this amazing scroll library. What would really be helpful is to have demos of each property after setting up and initializing it like we see in case of many other libraries that provide a use case for each aspect.

**Comment by devenini** [comment]
Hey! Our new version (v5.0) is currently in beta, but it comes with a complete documentation including simple demos and examples. See https://scroll.locomotive.ca/docs
