### ISSUE TITLE
How do you use this library for scroll-linked rotation or scaling effects?

### ISSUE THREAD

**Issue by ajayns** [locomotivemtl/locomotive-scroll#51]
In some cases, I'd like to have some control over the scrolling transform. It possibly could be a custom callback function on scroll with the translate value that I could use for added transforms.

**Comment by quentinhocde** [comment]
Hello,

You can simply use the on `scroll` event and update the style of your element with the scroll value like this :

```
scroll.on('scroll', (instance) => {
    console.log(instance.scroll.y);
});
```

Thanks :)

**Comment by ajayns** [comment]
Thank you @quentinhocde, the quick reply is much appreciated! :)
