### ISSUE TITLE
V5 data-scroll-direction

### ISSUE THREAD

**Issue by himonoonna** [locomotivemtl/locomotive-scroll#515]
Hi, thanks for your hard work to upgrade the latest beta version. It helped me solve the fixed positioning and background attachment problem, cause i don't have to write long javascript syntax

I want to make horizontal styles in the div element, but after reading the v.5 documentation, I noticed no "data-scroll-direction" attribute anymore (it appears in the previous version). it is defined only at the start (html tag), like this :
`html[data-scroll-orientation="horizontal"] {
    body {
        width: fit-content;
    }
    [data-scroll-container] {
        display: flex;
    }
}`

 My question is, how to use these attribute on the other elements and CSS classes?

**Comment by devenini** [comment]
Hey there! If you're aiming for horizontal scrolling, make sure to specify `orientation: 'horizontal'` under `lenisOptions` within the [instance options](https://scroll.locomotive.ca/docs/#/options?id=lenisoptions). This will add a `data-scroll-orientation` attribute to the `<html>` tag. Once you've done that, apply the [basic styles](https://scroll.locomotive.ca/docs/#/quickstart?id=horizontal-styles) for horizontal scrolling.

Feel free to check out the [horizontal demo](https://scroll.locomotive.ca/demo/horizontal) as well.

**Comment by himonoonna** [comment]
Thanks for the replay and explanation.

On the website that I created, there is a one part in one of the sections where the direction is made horizontally.
An example can be seen in version [4.x](https://locomotivemtl.github.io/locomotive-scroll) , which in the **02.Section** section, the texts move horizontally and in opposite directions.

In the example above, the direction setting itself is set inside the `<span>` tag like the syntax below:
`<span class="c-direction-block_item_inner" data-scroll data-scroll-direction="horizontal" data-scroll-speed="6" data-scroll-target="#direction">`
  `I'm moving in this direction`
`</span>`

I hope in the future, `data-scroll-direction` feature can still be used inside other html tags in version 5.x

**Comment by devenini** [comment]
Hey! Horizontal parallax is no longer supported out of the box. However, you can achieve this effect quite easily using progress and custom events :

```html
<div 
    data-scroll 
    data-scroll-event-progress="horizontalParallaxEvent"
>
    <p id="parallaxTarget">I'm moving in this direction</p>
</div>
```

```js
/* Locomotive scroll instance */
const locomotiveScroll = new LocomotiveScroll();

const $parallaxTarget = document.getElementById("parallaxTarget");

window.addEventListener("horizontalParallaxEvent", (e) => {
  const { progress } = e.detail;

  const parallaxDistance = 150;
  const translate = (1 - progress) * parallaxDistance;

  $parallaxTarget.style.transform = `translate3d(${translate}px,0,0)`;
});
```
