### ISSUE TITLE
continuous scroll loop content up and down 

### ISSUE THREAD

**Issue by adamjw3** [locomotivemtl/locomotive-scroll#52]
Hello 👋

anyway to loop the the content continuously?

had a go with a few demos but nothing solid 

https://codesandbox.io/s/heuristic-resonance-0ybkl

https://codesandbox.io/s/young-wind-ozeeq

https://codesandbox.io/s/patient-darkness-6gxj1

Thank you 👊

**Comment by quentinhocde** [comment]
Hi :)

There is no direct solutions to do this. 
This kind of feature is really specific and we want to keep an abstract library. 
You can try with 2 differents scroll section and move them depend on the scroll value.

Thanks!

**Comment by adamjw3** [comment]
@quentinhocde i've kind of got it working https://codesandbox.io/s/dazzling-benz-sbrmb (scroll towards the top)

The trick was the inertia setting,  is this passed down to the virtual scroll? can't see any documentation on this. any Pointers on my example would be great.

**Comment by adamjw3** [comment]
@quentinhocde could you advise on if this is possible with this wonderful package. 

https://pup.adamwright90.now.sh/

I've got it looping when scrolling up but can't get it looping when scrolling down. heres the code https://github.com/adamjw3/pup/blob/master/src/components/Scroller.js

Am i missing something?
