### ISSUE TITLE
Lenis wrapper not working in v5 beta 9

### ISSUE THREAD

**Issue by letstri** [locomotivemtl/locomotive-scroll#532]
Hello 👋

I use wrapper prop for my custom element. After 5.0.0-beta.9 scroll not working.

Steps to reproduce:
1. Install  "locomotive-scroll": "5.0.0-beta.9"
2.
```html
<div id="app">
  <div>
    A lot of content
  </div>
</div>
```
3.
```ts
import LocomotiveScroll from 'locomotive-scroll';

new LocomotiveScroll({
  lenisOptions: {
    wrapper: document.getElementById('app'),
  },
});
```
3. Scroll not working

Thank you 👊

**Comment by devenini** [comment]
Fixed in `v5.0.0-beta.11`

**Comment by letstri** [comment]
@devenini sorry but I have the same problem in 11

**Comment by devenini** [comment]
Could you please share a CodeSandbox replicating the bug? Thanks!
