### ISSUE TITLE
Changing scrollbar height to value other than 100vh is not respected

### ISSUE THREAD

**Issue by pavel-mazhuga** [locomotivemtl/locomotive-scroll#55]
Hi! First off, thank you for your work, it's amazing!
I have trouble making scrollbar (.c-scrollbar) height less than 100vh, (let's say 80vh). I apply necessary CSS before script initialization, but the thumb translates related to window height anyway. Am I missing something? I need the thumb translation to respect the scrollbar container height.

**Comment by quentinhocde** [comment]
Hi!

The issue is fixed in the `3.2.2` version in this commit : f98c0d8 
Now it's not relative to the window height (100vh), it's relative to your scrollbar height you set in your CSS.

Thanks :)

**Comment by pavel-mazhuga** [comment]
Thank you!
