### ISSUE TITLE
Links to Lenis are broken

### ISSUE THREAD

**Issue by bnjmnrsh** [locomotivemtl/locomotive-scroll#551]
Hello 👋

The links to the [lenis](https://github.com/studio-freight/lenis) repo are broken, including ones that I've found in the [documentation](https://scroll.locomotive.ca/docs/#/limitations) and in the GitHub description for [locomotive-scroll](https://github.com/locomotivemtl/locomotive-scroll/).

https://github.com/locomotivemtl/locomotive-scroll/
https://scroll.locomotive.ca/docs/#/limitations

**Comment by devenini** [comment]
Fixed
