### ISSUE TITLE
data-scroll-call not exiting when at the bottom of the page.

### ISSUE THREAD

**Issue by dominicht** [locomotivemtl/locomotive-scroll#57]
I'm using the data-scroll-call to know when some elements are in the viewport or not. This works fine and triggers an Enter/Exit event for all the elements in the middle of the page. However, when I apply data-scroll-call to the footer, only the Enter event will be triggered, but when I scroll back up and the footer is out of the viewport, the Exit is not triggered.

Any idea why?

**Comment by Jerek0** [comment]
Seems like you forgot to add the `data-scroll-repeat` attribute to your footer ?

**Comment by dominicht** [comment]
Hi @Jerek0, 

I will try the `data-scroll-repeat`, but I didn't want to use this for other reasons.

However, for elements that aren't at the bottom of the page (anywhere else) and that still don't have the `data-scroll-repeat` attribute, they have the Enter and Exit event, just not when it's at the bottom of the page. This doesn't seem like the intended behavior.

**Comment by quentinhocde** [comment]
Hi @dominicht, 

If you don't have a `data-scroll-repeat` you can't get the "2 directions" triggering. The repeat option allows to know if the element enter in viewport, or leave. If you don't set this attribute, you just can get the enter triggering.

Thanks!
