### ISSUE TITLE
Usage with js

### ISSUE THREAD

**Issue by snikhitha095** [locomotivemtl/locomotive-scroll#58]
I am using javascript and jquery, how can i use locomotive-scroll library without npm install?

**Comment by adamjw3** [comment]
download the zip of the repo and include the JS and CSS from https://github.com/locomotivemtl/locomotive-scroll/tree/master/dist

**Comment by snikhitha095** [comment]
I am not using ES6 i am using lower version of Javascript, how to import js files in another js file.

**Comment by antoineboulanger** [comment]
Hi, you don't have to import it, just include it on your page with a `script` tag. Also answered in issue #7 .
