### ISSUE TITLE
A way to jump to top for content replacement (without smoothing)

### ISSUE THREAD

**Issue by 23d1** [locomotivemtl/locomotive-scroll#61]
Would be great with a way to scroll to top (or element top with or without offset) without smoothing for when replacing content with XMLHttpRequests or AJAX. For example, navigating to another page with AJAX, as it transitions (hiding the previous content) it jumps to top before replacing (and revealing) the content so as not to be mid-smooth-scroll to target when revealed.

This is most likely related to #29 

My current solution is to `destroy()` and `removeAttribute('style')` on the container then `init()`. Seems like this could be handled with a third option in the `scrollTo(elem, offset)` like `scrollTo(elem, offset, true/false)` for smoothing, or simply resetting the transform matrix.

**Comment by Jerek0** [comment]
We'll look into that. For the moment you can use that combo:
```JS
myscroll.setScroll(0,0)
myscroll.update()
```

**Comment by Jerek0** [comment]
With `3.5.3` we added the `disableLerp` option so you also can use this now :
```JS
myscroll.scrollTo(0,0,0, undefined, true)`
```
