### ISSUE TITLE
Working with SPA

### ISSUE THREAD

**Issue by GoAndrew** [locomotivemtl/locomotive-scroll#62]
Hi!

Could you tell me please, how to update your scroll (fully) when I change page url? 
I tried every your methods, but it doesn't work well.

**Comment by adamjw3** [comment]
@GoAndrew can you provide example code

**Comment by regenrek** [comment]
@GoAndrew for instance with spa you need to destroy and reinitiate locomotive on every page. 

snippet
```
  mounted () {
    this.$nextTick(
      function () {
        this.lmS = new LocomotiveScroll({
          el: document.querySelector('#js-scroll'),
          smooth: true
        })
      }.bind(this)
    )
  },
  destroyed () {
    if (typeof this.lmS !== 'undefined') {
      this.lmS.destroy()
    }
  }
```

**Comment by antoineboulanger** [comment]
Hi, like @regenrek said, you can destroy and reinit the instance on every page change.
