### ISSUE TITLE
Problem with scroll detection plugins like scrollmagic

### ISSUE THREAD

**Issue by regenrek** [locomotivemtl/locomotive-scroll#63]
Hello 👋

Somehow locomotive has issues with scroll detection libraries like `scrollmagic`.
I also experienced the issue with other libraries like `vue-observe-visibility`.

I've built an example to understand the issue better: https://codesandbox.io/embed/nuxt-locomotive-scroll-scrollmagic-vdz1z?fontsize=14

Without locomotive (click on the second page on nav) it works as excepted but with locomotive it seems if the `<section id="change-nav-color" data-scroll-section>` triggers again as soon as the element gets style `"visibility:hidden"` from `data-scroll-section` attribute.

Any ideas?

Regards

**Comment by antoineboulanger** [comment]
Hi, Locomotive Scroll, with the smooth option, uses CSS transforms to scroll the page, for that reason, other scroll libraries won't work. On the other hand, you shouldn't need another scroll library, we already offer scroll detection and events.

**Comment by regenrek** [comment]
Hi

well I needed it for a certain use case. I got it working if you update scrollmagic with the `y` position from scrollmagic.

Sidenote: I also noticed that locomotive offers a `data-scroll-to` attribute which isn't documented yet - pretty handy.

**Comment by leonzuendel** [comment]
> Hi
> 
> well I needed it for a certain use case. I got it working if you update scrollmagic with the `y` position from scrollmagic.
> 
> Sidenote: I also noticed that locomotive offers a `data-scroll-to` attribute which isn't documented yet - pretty handy.

Whar do u mean? How ecactly did u fix it?

 Can you show an example? Having the same issue right now

**Comment by regenrek** [comment]
Its a long time since then. 

What I remember was to set the y position from scrollmagic manually somehow. 

But my honest suggestion is that you avoid mixing this two libraries. Its getting slow, I dont use scrollmagic anymore.
