### ISSUE TITLE
Snap section to the top

### ISSUE THREAD

**Issue by cmarcelly-plu** [locomotivemtl/locomotive-scroll#64]
Hi,

I'm trying to make sections with width at 100% and height at 100vh, snap to top when section is in view.

I tried to achieve it in calling stop() method first then scrollTo() method.

Example:

`this.scroll.stop()
this.scroll.scrollTo(section)

setTimeout(() => {
  this.scroll.start()
}, 1200)`

It doesn't snap perfectly to the top because of the easing of the scroll before calling stop() that continue, I suppose...

Is there a way to succeed snapping sections to top when scrolling or is it a feature you may add?

By the way great work you did! Thanks!

**Comment by adamjw3** [comment]
Do you have an example you can share?
have you tried playing with the inertia setting?

**Comment by ZachSaucier** [comment]
I'd like to create an effect like the "Featured Projects" section of this page https://katiforner.com/

**Comment by Jerek0** [comment]
Unfortunately that's not a feature we plan to add as it's very specific. 

That being said, it can be done! It's not an easy task though: you'll have to manage the behavior yourself with the help of `.start()`, `.stop()`, `.setScroll(x,y)` & `.update()` methods 😉
