### ISSUE TITLE
Scroll does not work when you press the keyboard buttons

### ISSUE THREAD

**Issue by DaveDev13** [locomotivemtl/locomotive-scroll#68]
Hello 👋

**Describe the bug**
If it is banal to press the button "home/end, page up/down", then nothing will happen. It is a trifle, but it is very pleasant when it works

**Expected behavior**
behavior as on normal pages:

1. page up/down-go to one screen
2. home/end-go to the beginning/end of the page

Thank you 👊

**Comment by antoineboulanger** [comment]
Hi, this issue is fixed in https://github.com/locomotivemtl/locomotive-scroll/commit/18f77878089b7543943c084a6648882dcaacdd95 and included in 3.2.8.
Thanks!
