### ISSUE TITLE
ES5 minimized version of the script

### ISSUE THREAD

**Issue by akabei** [locomotivemtl/locomotive-scroll#7]
Hello there!
How can I use your locomotive-scroll in ES5? Is there a minimized ready-to-use version which I can initialize and destroy as I need?

Thanks in advance.

**Comment by carlm-fieldtrip** [comment]
I also would love to use locomotive-scroll in ES5.

**Comment by antoineboulanger** [comment]
Hi, yes there is now in:
```
dist/locomotive-scroll.min.js
```
You can initialize it that way:
```js
var scroll = new LocomotiveScroll();
```
and destroy it:
```js
scroll.destroy()
```
