### ISSUE TITLE
When data-scroll-speed set to negative value element stop translating after certain point of the viewport?

### ISSUE THREAD

**Issue by sonupandit** [locomotivemtl/locomotive-scroll#76]
Please check url below 
https://codepen.io/pndtsonu/full/abzrJeX

I have added data-scroll-speed="-6" to an image. when i scroll down its stop translating after certain point.

Basically i want that image keep translating down until it's in viewport.

Thank you 👊

**Comment by antoineboulanger** [comment]
Hi, the translate stops when the bottom of the element's original position is outside of the viewport. What you can do is add `data-scroll-target="#wrapper"` to the element. It will use the wrapper position for the viewport detection instead of the element itself.

**Comment by sonupandit** [comment]
> Hi, the translate stops when the bottom of the element's original position is outside of the viewport. What you can do is add `data-scroll-target="#wrapper"` to the element. It will use the wrapper position for the viewport detection instead of the element itself.

Got it. Thank you!  :thumbsup:
