### ISSUE TITLE
Scrollbar thumb takes full height of the screen when page size is small

### ISSUE THREAD

**Issue by kasparsz** [locomotivemtl/locomotive-scroll#77]
Hello 👋

**Describe the bug**
If page size is just a little bit larger (for example by 100px) than viewport size then scrollbar thumbnail is larger than screen height.

Issue seems to be in https://github.com/locomotivemtl/locomotive-scroll/blob/master/src/scripts/Smooth.js#L262 
<pre>this.scrollbarThumb.style.height = `${(this.scrollbarHeight * this.scrollbarHeight) / this.instance.limit}px`;</pre>
This line should match https://github.com/locomotivemtl/locomotive-scroll/blob/master/src/scripts/Smooth.js#L248
<pre>this.scrollbarThumb.style.height = `${(this.scrollbarHeight * this.scrollbarHeight) / (this.instance.limit + this.scrollbarHeight)}px`;</pre>
but for some reason it's different. They should be setting the same value as far as I can tell.

If I replace line 262 with line 248 then it works correctly.

**Comment by antoineboulanger** [comment]
Thanks!
