### ISSUE TITLE
Data-scroll-call - Does not work for different functions

### ISSUE THREAD

**Issue by LaurieVince** [locomotivemtl/locomotive-scroll#79]
Hey, I'm Laurie.

I'm not sure how to use data-scroll-call with Locomotive Scroll. Perhaps I misunderstand the documentation, but when I try to call a function with data-scroll-call it always execute all functions. But I'd like to execute one function for each call.

This is what I wrote :
```
<div data-scroll data-scroll-call="test">Test 1</div>
<div data-scroll data-scroll-call="test2">Test 2</div>
```

```
function test() {
  console.log('This is a test.');
}
function test2() {
  console.log('This is the 2nd test.');
}
scroll.on('call', test);
scroll.on('call', test2);
```

I'm sorry if I did not understand. I hope you could understand my problem.
Thanks a lot,

Laurie.

**Comment by miguderp** [comment]
Check how they use it here: https://github.com/locomotivemtl/locomotive-scroll/blob/master/docs/src/scripts/main.js#L40

You pass three values to a function and `test` or `test2` should be the `value` parameter.

**Comment by LaurieVince** [comment]
Oh, it was easy! Thanks a lot!
