### ISSUE TITLE
Incorrect scroll limit height on Gatsby

### ISSUE THREAD

**Issue by ajayns** [locomotivemtl/locomotive-scroll#81]
**Describe the bug**
Page height is incorrectly measured by LS and so the scroll ends too early or a bit after the content ends. 
On deeper inspection, it seems that the `limit` on the scroll instance gets an incorrect value on initializing. I've tried fixing this by adding an `update()` call after a timeout to no avail. 

**To Reproduce**
1. Setup locomotive scroll on Gatsby
2. Add content to page and scroll

I'll attempt to provide a demo reproducing the error later, but if anyone has a CodeSandbox to show the issue that'd be great (cc @flowen)

**Expected behavior**
The scroll should happen till page end not before or after: technically the right value set to `limit`

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 80

**Comment by flowen** [comment]
Good catch on the prev issue. 

I got 2 codesandboxes with quite similar code but different bugs:

1. Here's where you see, a lot of extra whitespace is added on the bottom
https://codesandbox.io/s/epic-satoshi-d91fo

2. Based on the example supplied in #13 I added some titles and images. Every image does a scroll.update() onLoad, but the same white-space problem persists. I also added some transitions on scroll but it's all a bit buggy. 
https://codesandbox.io/s/locomotive-scroll-in-react-4ssov

**Comment by ajayns** [comment]
@flowen Trying out a couple of hacks I found one that seems to work (probably for specific cases I'm unsure):
* Use a setInterval function in the `useEffect` hook to call `scrollInstance.update()` regularly - this ensures that the limit and other values are set right values.
* Ensure that the `documentElement` or `body` has `overflow: hidden` so that just the node attached to LS translates and no external scroll occurs.

Check this out and let me know how it goes.

**Comment by vzrandom** [comment]
In my case if you destroy and reinit LS after 100ms it fixes the height problem. So it's probably just initialised too early

`
const scroll = new LocomotiveScroll({
   el: document.querySelector('#js-scroll'),
   smooth: true,
});

scroll.destroy()

setTimeout(function(){ 
 scroll.init()
}, 100); 

`

**Comment by ajayns** [comment]
@vzrandom Alternatively you could just call a `scroll.update()` after a certain timeout, but what for my case, it didn't seem to be enough. Maybe its dependant on internet speed and the amount of media content on the page? That's why I used a setInterval and that seemed to work fine cause of the regular checks.

**Comment by antoineboulanger** [comment]
Hey, can you guys continue this conversation in the issue #13. Thanks.

**Comment by ZachSaucier** [comment]
I'm seeing this problem (without Gatsby or any library) only on iOS. I'm guessing I should make a new thread?

**Comment by rphcompany** [comment]
I'm using it in NextJS and none of the solutions above works. I want my page to scroll smoothly and it only works of the height is added in the bottom. if I don't want the height I should forget about the smooth scrolling and just implement it on one of the elements inside the page like an image. 
I used `scroll.destroy()` and then with `setTimeout()` used the `scroll.update()` but again I get the extra-height. even If i don't do anything on the page and just implement the LS on the app with `data-scroll-container` all of my pages get the extra-height. pls someone help soon. thanks in advance

**Comment by alimeghnatis** [comment]
I'm using it in NextJS and none of the solutions above works. I want my page to scroll smoothly and it only works of the height is added in the bottom. if I don't want the height I should forget about the smooth scrolling and just implement it on one of the elements inside the page like an image.
I used scroll.destroy() and then with setTimeout() used the scroll.update() but again I get the extra-height. even If i don't do anything on the page and just implement the LS on the app with data-scroll-container all of my pages get the extra-height. pls someone help soon. thanks in advance

**Comment by Victor-Salomon** [comment]
> I'm using it in NextJS and none of the solutions above works. I want my page to scroll smoothly and it only works of the height is added in the bottom. if I don't want the height I should forget about the smooth scrolling and just implement it on one of the elements inside the page like an image.
> I used scroll.destroy() and then with setTimeout() used the scroll.update() but again I get the extra-height. even If i don't do anything on the page and just implement the LS on the app with data-scroll-container all of my pages get the extra-height. pls someone help soon. thanks in advance

Hey @alimeghnatis, did you find a solution to make it works and fixe the extra-height ? 
I wrapped my App with my LS function from context. It works but I can't figure out how to solve the extra-height.
Thanks by advance !!

**Comment by alimeghnatis** [comment]
> > I'm using it in NextJS and none of the solutions above works. I want my page to scroll smoothly and it only works of the height is added in the bottom. if I don't want the height I should forget about the smooth scrolling and just implement it on one of the elements inside the page like an image.
> > I used scroll.destroy() and then with setTimeout() used the scroll.update() but again I get the extra-height. even If i don't do anything on the page and just implement the LS on the app with data-scroll-container all of my pages get the extra-height. pls someone help soon. thanks in advance
> 
> Hey @alimeghnatis, did you find a solution to make it works and fixe the extra-height ?
> I wrapped my App with my LS function from context. It works but I can't figure out how to solve the extra-height.
> Thanks by advance !!

Hi no I did not. couldn't find nothing on the net and even a few pro coders i sent to said it takes too much time to solve if it does solve. so I just forgot about it. sorry to disappoint you

**Comment by BrandonLandgraffBranding** [comment]
@vzrandom 

You solved my issue! Took me 4 hours to figure this one out! APPRECIATE YOU!

**Comment by jordan-umbrace** [comment]
> scroll.destroy()
> 
> setTimeout(function(){ scroll.init() }, 100);

This helped me, except for the part that it sends me to the top of the page on each click?? Does anyones has ahd experience with this?

**Comment by Victor-Salomon** [comment]
@Jerek0  
(I copy/paste this comment from an older ticket issue to this issue #81 as it look newer)
Hello,
Is there any other fix than instance.update() on a Next Js project ? .update() even with the timeout does not fix the large space after container and if I add the overflow hidden or a min-height 100vh, the page is too small.
I tried probably all the fixs I've found on internet but it does not work... 
Thank you anyway to everyone improving the smooth scroll !
