### ISSUE TITLE
Minimal demo and simple example usage

### ISSUE THREAD

**Issue by LittleHamster** [locomotivemtl/locomotive-scroll#84]
I am not sure how to setup this, based on some existing issues, I included the css and js from here: https://github.com/locomotivemtl/locomotive-scroll/tree/master/dist

then in my main js file

```
$( document ).ready( function() {
....
const scroll = new LocomotiveScroll({
    el: document.querySelector('#js-scroll'),
});
....
} );
```

but now what? adding this code: 
```
<h1 data-scroll data-scroll-speed="1">Hello</h1>
<p data-scroll data-scroll-speed="2">Text</p>
```
does not make any changes

**Comment by devenini** [comment]
Hello @LittleHamster ,

You may refer to this [demo](https://locomotivemtl.github.io/locomotive-scroll/). Source files can be found [here](https://github.com/locomotivemtl/locomotive-scroll/tree/master/docs).

Make sure the `<html>`, `<body>` and scroll container are in `overflow: hidden` (refer to the demo) 

If you want smooth scrolling, you'll have to add `smooth: true` in your LocomotiveScroll instance. All the options can be found [here](https://github.com/locomotivemtl/locomotive-scroll#instance-options)
