### ISSUE TITLE
Check whether window.location.hash is a valid selector before scrolling to it

### ISSUE THREAD

**Issue by sergiocerrutti** [locomotivemtl/locomotive-scroll#85]
**Is your feature request related to a problem? Please describe.**
Currently I'm using [Snipcart](https://snipcart.com), this ecommerce layout adds a hash to the URL when is loaded `#/`. This is not a problem, but Locomotive Scroll thinks it's an internal anchor and tries to scroll to it, getting the following error:
`Failed to execute 'querySelectorAll' on 'Document': '#/' is not a valid selector.`

**Describe the solution you'd like**
It would be great and safer to check the hash is a valid selector before scrolling to it.
The line I'm talking about: https://github.com/locomotivemtl/locomotive-scroll/blob/cf3ffb2f76b3bb5c8b3710d6a9bc73a8d37048bd/src/scripts/Main.js#L27

**Describe alternatives you've considered**
Another alternative is to add an option in the config to avoid this default behavior, but I think it's not the best solution.

**Comment by Jerek0** [comment]
Hi and thanks for the feedback! This is fixed by 56cf42149c80cf52f7136050f755367947617fba 👍
