### ISSUE TITLE
Maximum call stack size exceeded error with 3.3.4 when calling update()

### ISSUE THREAD

**Issue by weotch** [locomotivemtl/locomotive-scroll#86]
Hello 👋

**Describe the bug**
I'm getting a `Maximum call stack size exceeded` error when calling `update()` since 3.3.4 (and #82 was merged):

![Screen Shot 2020-02-20 at 9 58 31 AM](https://user-images.githubusercontent.com/77567/74964043-8e58c100-53c7-11ea-8144-08612c599511.png)

My guess is that [the addition of `checkScroll()` within `setScroll()`](https://github.com/locomotivemtl/locomotive-scroll/blob/master/src/scripts/Smooth.js#L616) is causing an infinite loop.

**To Reproduce**
1. Go to https://codepen.io/weotch/pen/GRJjwJN
2. Check the console to see the error

**Expected behavior**
No errors

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 79.0.3945.130

Thanks for the great package!

**Comment by Jerek0** [comment]
Thanks for the heads up! It was indeed a bit dumb 🙃

**Comment by weotch** [comment]
Yup, that fixed it!  Thanks for the quick turnaround 🍻
