### ISSUE TITLE
[Bug] `is-inview` class missing on Native again

### ISSUE THREAD

**Issue by regenrek** [locomotivemtl/locomotive-scroll#88]
Hello 👋

we discovered that some elements don't get the `is-inview` class if you scroll in view. Here is a Screenshot of the official locomotive landingpage where you can see the issue which happens mostly on mobile devices. 

![image](https://user-images.githubusercontent.com/5182020/75091725-c9e2bf00-5570-11ea-8020-0901df13b523.png)
![image](https://user-images.githubusercontent.com/5182020/75091807-af5d1580-5571-11ea-85a7-399b4b457a0b.png)

We also discovered the problem on one of our pages here: https://www.bausteff.at

Did maybe some of the latest changes breaks this behaviour since it was already fixed with https://github.com/locomotivemtl/locomotive-scroll/issues/36 . 

Thank you 👊

**Comment by KerneggerTim** [comment]
After some tests I can confirm that this issue starts with 3.3.0. (It works on 3.2.9)

**Comment by Jerek0** [comment]
Thanks for the heads up! 👍
