### ISSUE TITLE
GSAP 

### ISSUE THREAD

**Issue by dejan-77** [locomotivemtl/locomotive-scroll#89]
Hi, i'm trying to trigger GSAP timeline with call event, but with zero success
Could someone be so kind and show me some simple piece of code, for example, data-scroll-call trigger in & out GSAP tween on some object. Some basic example :) Thank you

**Comment by regenrek** [comment]
Hi,

you can look at this [issue](https://github.com/locomotivemtl/locomotive-scroll/issues/20) or especially this example: https://codesandbox.io/s/codesandbox-nuxt-mhobt 
This should give you some boilerplate to add your gsap methods to it.

**Comment by dejan-77** [comment]
Thank you for help! Will jump into it 😎 👍

**Comment by adamcoulombe** [comment]
Here is an approach to combining gsap with locomotive-scroll's `on('scroll')` handler.

https://codesandbox.io/s/modest-shape-4l02e?fontsize=14&hidenavigation=1&theme=dark

basically `on('scroll')` I iterate over elements that have a `data-scroll-timeline` attr... then I use that to reference a timeline and use gsap's `seek()` method to go to the appropriate frame according to its vertical progress within the viewport. Hope that makes sense -  take a look at the code in the link (it is in  a React environment, but could easily be adapted to however you are using it)

**Comment by dejan-77** [comment]
Hey Adam, that's great! I understand the concept, but unfortunately, i can't adapt it from react to plain js since my current knowledge is not so great at this moment. how can i convert this part:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.timelines = {};
  }
  componentDidMount() {
    this.timelines["fast-spin"] = gsap.to("#welcome", {
      rotation: "1080",
      paused: true
    });
   });
```
after that i use code from line 20 - 45?

also, can i reuse it on multiple elements, or i need to duplicate it for every element

sorry for so many questions and thank you for helping :) 
cheers

**Comment by adamcoulombe** [comment]
Heres an example without the react:
https://codesandbox.io/s/vigorous-germain-kxbdh

with this approach, any element you put a `data-scroll-timeline` on each needs its own tween/timeline. Otherwise you'd have more than one trigger element potentially trying to control the same tween, which would probably be weird.

If you need mutiple elements basically doing the same animation, just create multiple identical tweens.

**Comment by Jerek0** [comment]
@adamcoulombe's last proposal is a good basis and simple to use! 👍 

### A few notes on performance
It could be optimized by:
- (easy) storing the list of `timelineEls` outside of the scroll listener to avoid calling expensive `document.querySelectorAll` on each scroll event
- (hard) computing and storing all `timelineEls` coordinates outside of the scroll listener to avoid calling the other expensive method which is `elem.getBoundingClientRect` on each scroll event. This way you could use current scroll value given with the scroll event and compare with your stored coordinates to compute the progress of your timelines. We use that concept to manage `data-scroll` elements inside LS.
  -  That increases performance (especially when your page is getting bigger), but it's harder to manage and also requires proper handling of a layout changes (e.g. accordion opened, resize event or an image load that lengthen the scroll size) to update coordinates. 😉 Also, forget it if you use any `data-scroll-section` unless you want a strong headache.

**Comment by dejan-77** [comment]
thank you very much guys, it works! :))) @adamcoulombe @regenrek 
@Jerek0 thank you for the performance notes :) can you, please, write example code how to optimise it further with your (easy) method (storing the list outside scroll listener). beginner here :) i understand the concept but could not yet translate it to code. i appreciate any help ♥️ thanks again

**Comment by adamcoulombe** [comment]
@dejan-77 
![code example](https://i.ibb.co/zfhxt7J/image.png)

**Comment by dejan-77** [comment]
thank you!

**Comment by ariwoot** [comment]
Hello @adamcoulombe, thank you for the precious example. 
You said that it can be applied to its own tween/timeline. 
I tried adapting it to a gsap timeline but it doesn't animate the element. 
This is what i wrote instead of the tween in the example:
```
let tlAlbed = gsap.timeline();
      tlAlbed.to('.albed-text', 1, {
        color: '#e6e6e6',
        paused: true
      }).to('.albed-text', 1, {
        filter: "blur(6px)",
        paused: true
      })

      timelines["albed-anim"] = tlAlbed;
```

In the console log I get this: 
```
Timeline {vars: {…}, _tDur: 0, _dur: 0, _delay: 0, _repeat: 0, …}
vars: {}
_tDur: 0
_dur: 0
_delay: 0
_repeat: 0
_ts: 1
data: undefined
_start: 8.286
_end: 8.286
_next: undefined
...

```

While with a simple tween I have: 
```
Tween {vars: {…}, _tDur: 2.7, _dur: 2.7, _delay: 0, _repeat: 0, …}
vars: {duration: 1.5, filter: "blur(20px)", stagger: 0.3, paused: true, overwrite: false, …}
_tDur: 2.7
_dur: 2.7
_delay: 0
_repeat: 0
_ts: 0
data: undefined
_start: 0.853
_end: 3.553
... 
```

Do you know for a chance a proper way to make this system work with a timeline?
Thank you again
