### ISSUE TITLE
Skips first scroll movement

### ISSUE THREAD

**Issue by web2033** [locomotivemtl/locomotive-scroll#9]
It skips the very first scroll-wheel move. Second and later sequence work. Then, if paused for a moment - again skips first scroll move.

Checked in Chrome 75, Edge 18.

**Comment by xavierfoucrier** [comment]
I have this issue too: if you try to scroll up/down, the first scroll step is skipped. Try to scroll with the first step up, then down, then up, then down, etc. do nothing on the official locomotive-scroll website.

Chrome 75.0.3770.142

**Comment by quentinhocde** [comment]
Hello,

I guess this bug was fixed in a commit after because I can't reproduced it now 🧐

Thanks

**Comment by web2033** [comment]
@quentinhocde I just tried it on your demo page
https://locomotivemtl.github.io/locomotive-scroll/
and it still there, Chrome/Edge/83

**Comment by quentinhocde** [comment]
Ok I get it, should be good with the 3.5.2 release. 
You can test it on the demo page

Thanks
