### ISSUE TITLE
css overflow hidden blocks scroll

### ISSUE THREAD

**Issue by ariwoot** [locomotivemtl/locomotive-scroll#93]
Hello everyone, 
I've just installed locomotive-scroll through npm in an angular8 environment. 
After having set up the basic example that's on the documentation, i'm encountering what seems a banal issue. 
I can't scroll after the first section cause class 'html.has-scroll-smooth'  has overflow: hidden. 

To start testing it i put almost the same code on docs after some sections in my page. I attributed to all the sections i want to scroll 'data-scroll-container':

**file.html**

```
<section data-scroll-container>
     <app-reference></app-reference>
</section>
<section data-scroll-container>
    <div data-scroll-section>
    <h1 data-scroll data-scroll-speed="1">Hello scroll</h1>
    <p data-scroll data-scroll-speed="2">
        Duis nec ipsum lobortis leo cursus elementum a vel urna. 
      </p>
</div>
</section>
```

**file.ts**

```
import LocomotiveScroll from 'locomotive-scroll';

ngOnInit() {
this.scroll = new LocomotiveScroll({
      el: document.querySelector('[data-scroll-container]'),
      smooth: true
});
}
```

Any suggestion about what I'm doing wrong, or could have gone wrong during installation/inizialization will be suuuper appreciated. 
I know it's a dumb issue but i'm stuck. 
Thank you in advance!

**Comment by antoineboulanger** [comment]
Hey, currently you only init LocomotiveScroll on one of the containers (`querySelector` gets the first one). 
I'm not sure what the `app-reference` does but If you wanted a single scroll on your page, you should only use 1 `data-scroll-container` that wraps everything. 
If you want 2 different instances of Locomotive Scroll, you need to initialize it twice with an ID on each.

```js
this.scroll1 = new LocomotiveScroll({
      el: document.querySelector('#container1'),
      smooth: true
});
this.scroll2 = new LocomotiveScroll({
      el: document.querySelector('#container2'),
      smooth: true
});
```

**Comment by ariwoot** [comment]
Hello and thank you so much, 
it works now, simple as that. 
I misunderstood the usage, I thought it had to be applied on single sections in order to work. 
Now i'll start integrating it with the project, thank you for having shared this with the community.
Have a good day!
