### ISSUE TITLE
Content missing/stuck after resize in IE

### ISSUE THREAD

**Issue by KerneggerTim** [locomotivemtl/locomotive-scroll#94]
Hello 👋

**Describe the bug**

1. After resizing the IE window the content freezes but the scrollbar is still working.
2. After scrolling and resizing the content disappears but the scrollbar is still working.

**To Reproduce**

Freeze error:
1. Open IE
2. Go to https://locomotivemtl.github.io/locomotive-scroll/
3. Resize the window
-------------
Disappear error:
1. Open IE
2. Go to https://locomotivemtl.github.io/locomotive-scroll/
3. Scroll down and resize the window

**Expected behavior**
You should be able to see the content and to scroll through the page

**Screenshots**
Freeze error:
![image](https://user-images.githubusercontent.com/59170152/75542417-15d5ae00-5a20-11ea-90a2-fd5c8a3897e6.png)
-------------
Disappear error:
![image](https://user-images.githubusercontent.com/59170152/75542497-3dc51180-5a20-11ea-8908-c9149d91be95.png)

**Desktop:**
 - OS: Windows
 - Browser: IE
 - Version: 11

Thank you 👊

**Comment by arg-1138** [comment]
Still waiting for anyone who can find a workaround to this.

 @KerneggerTim did you find any solution?

**Comment by Jerek0** [comment]
Thank's for the heads up! 🙂
To fix this please update LS to `3.4.4`

**Comment by Ginikachuqu** [comment]
Scroll bars disappear when I try to use the scroll feature in firefox and chrome. How do I fix this?

**Comment by FZMSH** [comment]
while use locomotive scrollbar with gsap .my website stuck and misbehave ..Don't know how to fix this issue..anyone can help
