### ISSUE TITLE
Lazy load images

### ISSUE THREAD

**Issue by podrivo** [locomotivemtl/locomotive-scroll#95]
I was wondering if it's possible to use Locomotive Scroll with an external lazy load plugin or even a native solution like `loading='lazy'`. Thanks!

**Comment by antoineboulanger** [comment]
Hey, if you want to load images while scrolling, you can use `data-scroll-call` with something like [this](https://github.com/locomotivemtl/locomotive-boilerplate/blob/master/assets/scripts/modules/Scroll.js#L25-L35). 
If you want to load all the images after the rest of the page is loaded, we use [modularLoad](https://github.com/modularorg/modularload) with `data-load-src`. 
You can see a demo page with both ways in our [boilerplate](https://github.com/locomotivemtl/locomotive-boilerplate/blob/master/www/images.html#L36-L76).

**Comment by podrivo** [comment]
Thank you, @antoineboulanger ! 😃

**Comment by dejan-77** [comment]
hey guys, is lazy load possible without React? like plain JS? thanks! 👍

**Comment by Jerek0** [comment]
@dejan-77 the code that @antoineboulanger mentioned above is plain JS 😉

**Comment by dejan-77** [comment]
hey @Jerek0 thank you for quick response  ☺️  newbie here so sorry for the amateur hour questions :D Antoine mention 2 ways for lazy load, one with data-scroll-call but i can not figure do i need all this code (marked in red are things that confuses me, specially "this.")?  
![Screen Shot 2020-03-03 at 19 37 11](https://user-images.githubusercontent.com/31392278/75809774-96cad780-5d89-11ea-9240-495dde1ef96a.png)
and second way with **modularLoad** - can i also use it without React? if yes, can i just load script like this: <script src="https://cdn.jsdelivr.net/npm/modularload@1.2.5/dist/main.cjs.min.js"></script>
thank you for help 👍 😊

**Comment by dejan-77** [comment]
Hi, anyone willing to help with this one? I tried everything, and it just don't work. 😊 thankyouuu

**Comment by podrivo** [comment]
I couldn't make it work either, with the provided examples.
Tried using `loading='lazy'`, which works, but breaks everything else.

**Comment by dejan-77** [comment]
> I couldn't make it work either, with the provided examples.
> Tried using `loading='lazy'`, which works, but breaks everything else.

hey @podrivo  did you succeed? 😎 cheers

**Comment by ZachSaucier** [comment]
@antoineboulanger When you say, "we use modularLoad" do you mean that it is bundled with Locomotive Scroll automatically? Or that you use it _in addition_ to Locomotive Scroll to lazy load images?
