### ISSUE TITLE
fixed element needs to be in the same stack context for z-index purpose 

### ISSUE THREAD

**Issue by ariwoot** [locomotivemtl/locomotive-scroll#96]
Hello!
I'm encountering a problem which is just effecting the css z-index property but i can't find a way to make this work. 
I'll put an simplified example code of the situation:
```
<div class="fixed-text" style="position: fixed; z-index: 200;">T E X T</div>
<div id="scroll-container" data-scroll-container>
<section class="section--1>
<div class="section--1--left" style="position: relative; z-index: 300;">left section should be on top of T E X T</div>
<div class="section--1--right" style="position: relative; z-index: 100;">right section should be under T E X T </div>
</section>
</div>
```

This would work, except that having added the data-scroll-container, it applies to #scroll-container a trasform: matrix property, which puts the element in a new stacking context. 
Of course, if i put the fixed element inside the data-scroll-container it will make it scroll according the the translation. 
What remain (that i can think of)  is moving the .section--1--right outside #scroll-container, but it needs to scroll at the same logic of the rest. This blocks me cause i've tried adding a data-scroll-container attribute to it but it doesn't work and neither sounds like the right way to reach this goal. 
Do you know a method to make two elements have the same scrolling logic even if they're not in the same #scroll-container? 
Or in alternative, am i missing something and i could easily reach this using css? 
Thank you so much!

**Comment by Jerek0** [comment]
Hi! In that case you need to use `data-scroll-sticky`. You can see an example here : https://locomotivemtl.github.io/locomotive-scroll/#fixed-elements
https://github.com/locomotivemtl/locomotive-scroll/blob/605e571aaf96f64c8051caa83d8f2db2167e6690/docs/index.html#L320-L346

**Comment by ariwoot** [comment]
Hi @Jerek0, first of all, thank you for the reply. 
Before posting this issue i tried to use data-scroll-sticky (without adding a data-scroll-target), and I failed.
Now, seeing the example you linked here, I changed the structure to resemble this index.html part, but i'm still getting no results. 
This is how i structured it (simplifying):

```
<div id="scroll-container" data-scroll-container>
<!-- fixed part -->
<div id="fixed-elements">
<div data-scroll data-scroll-sticky data-scroll-target="#fixed-elements">
<div class="fixed-text" style="position: relative; z-index: 200; height: 100vh; width: 100vw;">T E X T</div>
</div>
</div>
<!-- end of fixed part -->
<section class="section--1>
<div class="section--1--left" style="position: relative; z-index: 300;">left section should be on top of T E X T</div>
<div class="section--1--right" style="position: relative; z-index: 100;">right section should be under T E X T </div>
</section>
</div>
```

From what i understood from the demo, the mechanism in order to fix an element inside, is to make it translate counter-current, but inspecting my code the matrix3d doesn't change. I saw that there's no css affecting the positioning in the demo, so maybe i'm missing some js code for the sticky part or some html parts?

The "fixed section" is the first element showing (overlaying section--1), i put it some sections below to be sure that it wasn't a missed trigger thing, but still no results. 

I'm definitely doing something wrong... that's the only sure thing haha
