### ISSUE TITLE
2 x <span class="c-scrollbar">

### ISSUE THREAD

**Issue by bpetrieux** [locomotivemtl/locomotive-scroll#98]
Does anyone else have 2 c-scrollbar span in their code?

2 x <span class="c-scrollbar"><span class="c-scrollbar_thumb"></span></span>

![Capture d’écran 2020-03-06 à 14 13 07](https://user-images.githubusercontent.com/4721211/76114738-c90c4d00-5fb4-11ea-9e75-0b7baea0f12e.png)

Thank you 👊

**Comment by arg-1138** [comment]
That happened to me using nuxt, instancing a new LocomotiveScroll on each page without destroying it before.

**Comment by nathdhim** [comment]
how could you fixed this issue ?
